### PR TITLE
Create Pacman Game workshop readme.md

### PR DESCRIPTION
**Pull request by YashKalbande**
Complete every requirement for the good workshop, except 1-2 mins video which will be done in 1-2 day.
- [x] Workshop that meets all of the "Good workshops" guidelines outlined above

- [x] 1-2 minute video clip from your test club meeting showing what members built

- [x] All assets (images, PDFs, and any other binaries) must be hosted using the #cdn channel on the Hack Club Slack for posterity and to cut down on repository size. Images must include alt text (Markdown guide). Code snippets should be included in the text (not as screenshots) and preferably syntax-highlighted.

- [x] All workshops must involve code, and not require desktop software or hardware, since not all clubs will have those resources

- [x] You must be either a registered Hack Club leader or an active member of the Slack
- [x] All workshops must be in English at native-level proficiency. Phrasing and grammar must be perfect.

### CODE REVIEW

**Comment by wollygfx** [comment]
Man, this is awesome!

**Comment by YashKalbande** [comment]
@MatthewStanciu can you please review my workshop. It has been a week ago I submitted my workshop. Hope to hear from you soon.

**Comment by faisalsayed10** [comment]
Hii, we need the video clip in order to be eligible for the bounty.

**Comment by YashKalbande** [comment]
@faisalsayed10 Hi, so without video clip my workshop will not be reviewed? Can you and your friends join me to record video clip. Let me know if you are interested.

**Comment by MatthewStanciu** [comment]
Hey @YashKalbande, we require the demo clip to be submitted before I can begin reviewing your workshop. You should post in #workshop-bounty and see if you can get 2 people to join you!

**Comment by YashKalbande** [comment]
Hi @MatthewStanciu, [](https://hackclub.slack.com/archives/C01A9V5LPD0/p1604720005018500) this  is the link to the workshop video clip.

**Comment by MatthewStanciu** [comment]
Wow, this is so cool! This is way closer to being able to merge than your last workshop—great work. There are still a few problems with the workshop that need to be addressed before it's merged:

- Although your grammar, punctuation, and phrasing is good, there are still a few areas with weird capitalization, spelling, or punctuation. Not many, but I noticed a few somewhere. (for example, at one point there's no space between a period and the next sentence). Overall it's really good, but I think you should do one more deep dive and make sure everything's at 100%. It's okay if you don't find much though, because it's pretty good!
- The first image is broken
- Overall, this workshop's biggest problem is a lack of explanation. It feels like a lot of code is being given, but it's not very easy to understand, and the workshop doesn't explain a lot of it. What's the freegames library? What's turtle? In the middle of the workshop, you write a lot of code that calculates offsets, works with vectors, does a lot of math, and none of this code is explained. I think the most important changes you should make are going through and explaining each part of the code. For example, the `move()` function is dumped in its entirety—a lot of code—and I don't understand it.
- You should include the final code at the end, or check in frequently with "the code so far" (whichever feels more right to you), just so that the person going through the workshop always has context.
- Make sure to include the link to the demo and code at the beginning of the workshop

Once you've made these changes, feel free to reopen, then DM me on Slack so that I can re-review. I think after one or two rounds of changes, this will be ready to merge!

**Comment by YashKalbande** [comment]
@MatthewStanciu, (https://github.com/hackclub/hackclub/pull/1439) is the link to the new pull request with all the above changes are completed. Please review it. 

Will you please help in "How to reopen pull request?" as there is no button available below, or what is the correct way to reopen PR.

**Pull request closed without merging**
