### PR TITLE
Remove unfinished sections from personal website

### PR DESCRIPTION
**Pull request by MaxWofford**
STILL IN PROGRESS

### CODE REVIEW

**Comment by zachlatta** [comment]
How's this going?

On Tue, Feb 16, 2016 at 2:58 PM, Max Wofford <notifications@github.com>
wrote:

> STILL IN PROGRESS
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/hackclub/hackclub/pull/723
> Commit Summary
>
>    - Remove unfinished sections from personal website
>
> File Changes
>
>    - *M* workshops/personal_website/README.md
>    <https://github.com/hackclub/hackclub/pull/723/files#diff-0> (660)
>    - *D* workshops/personal_website/img/css_text_align_center.gif
>    <https://github.com/hackclub/hackclub/pull/723/files#diff-1> (0)
>
> Patch Links:
>
>    - https://github.com/hackclub/hackclub/pull/723.patch
>    - https://github.com/hackclub/hackclub/pull/723.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/723>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by MaxWofford** [comment]
@zachlatta going well. I'm redoing the Google section right now, after that should be good to go. ETA is end of Thursday (I have another day off).

**Comment by zachlatta** [comment]
:+1:

On Wed, Feb 17, 2016 at 4:56 AM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> going well. I'm redoing the
> Google section right now, after that should be good to go. ETA is end of
> Thursday (I have another day off).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/723#issuecomment-185189337>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
Going to close this for the time being.

**Pull request closed without merging**
