### PR TITLE
Reddit Client using Flask

### PR DESCRIPTION
**Pull request by KaiDevrim**
https://github.com/hackclub/hackclub/pull/1459

Finished all the issues that SamPoder left.

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
Thanks for adding the changes! I still think the POST part needs more context, specifically the python code and the demos could explained more professionally with paragraphs or a list etc.

like

- DEMO 1 NAME - This demo does...
- DEMO 2 NAME - This demo does...
- DEMO 3 NAME - This demo does...

or smth

thanks! 

sam

**Comment by KaiDevrim** [comment]
@sampoder How would I go about reopening a PR also?

**Comment by sampoder** [comment]
@KaiDevrim dm me on slack, and I can reopen it for you

**Comment by KaiDevrim** [comment]
@sampoder im ready for the next review, thanks!

**Review by sampoder — APPROVED** [review]
🚀 Congratulations!

**Comment by MatthewStanciu** [comment]
Hey @KaiDevrim 👋 I have some bad news unfortunately...

I've been putting this workshop off because I wasn't really sure how to handle it. I still think it needs some work, but for other workshops that have needed work I've stepped in and made those changes myself. But I couldn't do it for this workshop. I think a large part of it is that I feel like the final product just isn't compelling enough, and I don't feel like I would be able to run this in my own club meeting. And something that contributes to _that_ is that I feel like by this point, a lot of other workshops that cover the same topic, in both the same language and different languages, have presented the topic in a better way.

So right now, here's where my head is at: I don't think I can merge this workshop. But I also recognize the effort you've put into it, and I recognize that this was originally one of the first bounties submitted, and I don't want your effort to go to waste. So, if you're up for it, I'd love to send you $50 for this workshop in recognition of your efforts. I know you also have another workshop in the pipeline, so you could potentially get some more money from that one too.

If you want to take me up on the $50 offer, can you fill out the form at hack.af/bountypayment? Then I'll get you paid ASAP. And of course if you want to talk through it, feel free to DM me on Slack.

Sorry I don't have better news. Thank you so much for all of the effort you've put into this 💖

**Pull request closed without merging**
