### PR TITLE
Use repl.it filenames in Workshops, closes #1163

### LINKED ISSUE #1163: Workshops use index.css, repl.it uses style.css
The starter workshops assume this:
index_css-8b65e5a052a2256ab295dfb7883ca00d-b9b2f
but repl.it's default file names are:
screenshot 2018-11-12 13 00 35

### PR DESCRIPTION
**Pull request by dinaelhanan**
Changed all the images for the starter tutorials to reflect the proper repl.it default file names. The first two commits were just me figuring out were the images are kept in. Tried my best to follow the guidelines [here](https://github.com/dinaelhanan/hackclub/blob/master/CONTRIBUTING.md#git-commits) but if anything's off let me know.

### CODE REVIEW

**Comment by MaxWofford** [comment]
Thanks for the contribution @dinaelhanan! Can you also update the mentions of `index.css` to be `style.css` in the text and code examples?

**Comment by dinaelhanan** [comment]
@MaxWofford Will do

**Comment by dinaelhanan** [comment]
Ok I think I got all of them 👍

**Comment by lachlanjc** [comment]
Thanks a lot!! Looks good to me. @MaxWofford anything else?

**Comment by MaxWofford** [comment]
@dinaelhanan Thanks for addressing this!

**Comment by dinaelhanan** [comment]
@MaxWofford  No problem! I found more of these (ex. in the sketch together workshop) that I didn't catch. I'll keep working on them but I think the issue should be re-opened.
screenshot from 2018-11-19 10-55-21

**Comment by MaxWofford** [comment]
Just reopened https://github.com/hackclub/hackclub/issues/1163

**Comment by dinaelhanan** [comment]
woops.. just re-read the page and it was talking about VSCode and not repl. Should I still change it for consistency or..?

**Comment by MaxWofford** [comment]
@dinaelhanan: let's keep the conversation going in #1163 so anyone who sees this later can retrace the history. Just left a comment to you there

**Pull request merged**
