### PR TITLE
adding instructions on how to shallow copy

### PR DESCRIPTION
**Pull request by kazekagegaara**
PR for #753 , added instructions in README.md and CONTRIBUTING.md

### CODE REVIEW

**Comment by remixz** [comment]
Do you think we could replace `<repository-link>` with the actual link? In this case, `https://github.com/hackclub/hackclub.git`. As well, we should maybe briefly explain what a shallow clone is, in that it's a smaller copy of the repository because we're only downloading the latest changes, instead of a copy of all of the past changes.

**Comment by kazekagegaara** [comment]
@remixz I can add the explanation. For the link, it will be the link of the forked repository in most cases, that's why I used `<repository-link>` instead.

**Comment by remixz** [comment]
Ah, right! Makes sense. The previous step does link to a guide on forking, but just for clarity, maybe we should add where that repository URL comes from.

**Comment by remixz** [comment]
Looks great! :tada:

**Pull request merged**
