### PR TITLE
Add git_and_github workshop

### PR DESCRIPTION
**Pull request by MaxWofford**
**Not ready for merge; I'm still setting it up to pass the tests**

EDIT: Tests have passed! @jonleung Would you please review this?

Could I get your thoughts?@nguyenbrian @JevinSidhu @uditdesai @vaibhavyadaram

### CODE REVIEW

**Comment by jonleung** [comment]
@MaxWofford I am currently still sick and unfortunately don't have the bandwidth to review this carefully enough. In order for this to get merged in sooner, you'd need to enlist the help of someone else. Sorry : /

**Comment by MaxWofford** [comment]
@hackclub/hackclub Would anyone like to review this?

**Comment by sethtrei** [comment]
This is pretty good and could go well to be something to do after/before my workshop. Good job!

**Comment by JevinSidhu** [comment]
@MaxWofford Sorry for being so late on this! Must've missed the notification. 

This is absolutely awesome, thanks so much :)

**Comment by zachlatta** [comment]
Sorry @amysorto! Accidentally assigned you.

**Comment by zachlatta** [comment]
Looks good to me – some minor things, but I'll submit a pull request to fix those.

**Pull request merged**
