### PR TITLE
Update twilio promo code request email address

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by MaxWofford** [comment]
@zachlatta We should only merge this once the team email issues are worked out...

**Comment by zachlatta** [comment]
What if we just made our Twilio code public? Obfuscation through
obfuscation just seems... odd.

On Tue, Feb 23, 2016 at 8:54 PM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> We should only merge this once
> the team email issues are worked out...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/730#issuecomment-188068267>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
@zachlatta Good point. Replacing with https://github.com/hackclub/hackclub/pull/732

**Comment by zachlatta** [comment]
:+1:

On Tue, Feb 23, 2016 at 9:06 PM, Max Wofford <notifications@github.com>
wrote:

> Closed #730 <https://github.com/hackclub/hackclub/pull/730>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/730#event-562963893>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Pull request closed without merging**
