### PR TITLE
Rapid API Workshop - Draft 1

### PR DESCRIPTION
**Pull request by ayushtvora**
This is my first draft for my RapidAPI workshop. Please be sure to give me some advice on how I can improve it. Thanks!

### CODE REVIEW

**Comment by sampoder** [comment]
Hey! Workshops normally end with a end product, could we make this have an end product?

**Review by sampoder — CHANGES_REQUESTED** [review]
View above, also make sure all these guidelines are followed: http://hackclub.com/workshop-bounty/

**Comment by ayushtvora** [comment]
The end product was the Repl.it link near the end. [This is the end project](https://repl.it/talk/share/RapidAPI-Workshop-Example-1/54538) I have everything in the guidelines except for the video, which will be one of the last steps.

**Comment by sampoder** [comment]
Could we make the more prominent? I don't know what I'm making with the workshop. Sorry for not being clear.

**Comment by sampoder** [comment]
re: guidelines

below are the guidelines that need more to be done:

* End with at least 3 demos of how the project can be expanded, with live links and code links for each demo.

* Link unknown concepts to external sources.

* Video

**Comment by sampoder** [comment]
Lastly, just in general workshops have 300 lines of markdown, this one only has 60. Could we beef it up to 300?

**Comment by ayushtvora** [comment]
> Could we make the more prominent? I don't know what I'm making with the workshop. Sorry for not being clear.

I was trying to make it a little more open-ended and not too specific so that the members can look around and see what they can do with the different APIs. But I will work on making it more specific towards a certain goal, and afterwards, I can show off what other projects you can do using RapidAPI.

> End with at least 3 demos of how the project can be expanded, with live links and code links for each demo.

Sorry, but I am a little confused on what kind of demos you mean. Are these demos unique ways that the project can be presented, or am I misunderstanding it?

> Link unknown concepts to external sources.
> Lastly, just in general workshops have 300 lines of markdown, this one only has 60. Could we beef it up?

Okay, I will add more information and increase the learnability of the workshop by making more connections. As for only having 60 lines, I was scared that I would end up going over the time limit of 20 minutes if I made it any longer.

> Video

I was planning on making the video after the rest of the workshop is perfected, so it can be one final video at the end. If this is not the best idea, please let me know. Thanks!

**Comment by sampoder** [comment]
This should give you an idea of the kind of workshop you should be aiming for: https://workshops.hackclub.com/simple_clock/

**Comment by sampoder** [comment]
Video plan sounds fine

**Comment by sampoder** [comment]
Hey @ayushtvora, just for some housekeeping work on my end, what hack club do you lead?

**Comment by ayushtvora** [comment]
North Park Secondary School

**Review by lachlanjc — CHANGES_REQUESTED** [review]
Hey, I love this idea! And thanks for the submission. Unfortunately, this currently doesn’t meet our guidelines. You need to re-focus this workshop on outputting a real-world, usable project, with visuals throughout & significantly clearer explanations.

- Can you rename the workshop to focus on what you’re making? “COVID Tracker” or something
- You’ll need to add the metadata at the top—see the bounty program requirements for an example
- At the beginning of the workshop, before introducing technical concepts, please introduce the project itself. “We’re using an API to get statistics about the COVID pandemic, then inserting them into a webpage with JavaScript & jQuery.” for example
- I think the website itself should be much more fleshed-out: use some CSS for design, format the numbers, add details like last-updated, etc. The site it makes right now is too simple & bare-bones.
- You’re missing screenshots of the site, & links to the demo site & code
- These explanations are not nearly detailed enough about what to do for a beginner. Check out some other workshops on our site—they’re basically all in the hundreds of lines. Of course, length doesn’t equal clarity, but the instructions here don’t explain concepts thoroughly or describe really how to build the project with enough detail.
- Please link to documentation for more information about various topics, such as DOM manipulation, ajax requests, etc
- Please include the final source code of your project at the end of the coding sections—for example, the full JavaScript file.

To be blunt, this needs to be rewritten to meet our guidelines. But we’d love to have your workshop once it’s ready—this is an awesome project people would be super interested in!

**Pull request closed without merging**
