### PR TITLE
https://hackclub.slack.com/files/UJMRP65K9/F01AKQ9LW7R/tkinter_workshop.mp4

### PR DESCRIPTION
**Pull request by bezlin6mechminerz**
---
name:'Tkinter Workshop'
description:'We will use python tkinter graphics to make User Interfaces. Its a nice world.'
author: '@Bezlin Johnson'
---

# Final User Interface or UI.

Screenshot 2020-09-19 at 11 28 35 AM

This will be the simple UI we will be making today. This is nice world we can even make cool softwares with this .
Here is the [live_demo](https://repl.it/@bezlin/graphics#main.py) and [final_code](https://repl.it/@bezlin/graphics#main.py) (see src/app.js and public/app.css files).
This workshop will take 50 minutes.
ezgif com-video-to-gif

## Step 1 : SETUP

We will be using Tkinter python library to develop the user Interface.

### Setting up the environment for Tkinter

[Repl.it](https://repl.it) is a simple yet powerful online IDE, Editor, Compiler, Interpreter, and REPL. Code, compile, run, and host in 50+ programming languages.So it is super awesome.

To get started, go to https://repl.it/languages/Tkinter. If you cant find it just type it in the type box. Your coding environment will be ready in a few seconds!
Screenshot 2020-09-18 at 5 39 06 PM

## Step 2: Know the basics of Tkinter

Tkinter is a Python binding to the Tk GUI toolkit. It is the standard Python interface to the Tk GUI toolkit, and is Python's de facto standard GUI. Tkinter is included with standard Linux, Microsoft Windows and Mac OS X installs of Python. The name Tkinter comes from Tk interface.
Why Tkinter?
Tkinter provides a powerful object-oriented interface to the Tk GUI toolkit. Which can be customised and can look better.

## Step 3: Code and explanation.

Screenshot 2020-09-18 at 6 06 14 PM

### L1(line-1):

import
Import tkinter means we are importing a python library which is tkinter here . Actually someone clever made this library and made it open source. So we need to import it to our code to use it. Also for ease we imported tkinter as tk so that we no need to repeat that big word tkinter everytime. Instead we can use tk.

### For now lets skip L2 and L3 lets look at L4.

window

Here we have made a variable "window" and this is going to be our window. We need to make a window right . We are making a user interface so a window is needed. window=tk.Tk it means the tkinter developer already made a window and named it as Tk so we need to refer to that window and use the variable window as our window . So it means window = the library.the original window.

### L5

window minsize

Now we named our window as window .So we can adjust the size of the window .For that we use the function minsize(). This function takes 2 parameters the height and the width. It is measured as pixels like css but here we no need to specify px or any other units because the tkinter knows that the parameters are to be taken as pixels so we can simple give minsize(800,600) .So here we give 800px of width and 600px of height for our window.

### L6

title
Now we can set a title for our window. For that we use title() function .You can specify the name of the window inside the function in quotes.

### L7

config

In this line we are setting a background color to our window in this case i give black .You can also specify the color in hex code tkinter will accept it. Also is RGB too.
window.config means we are configuring our window and setting up its bg which is short form for background.

### L8

Label
This is a big line right? Dont worry its simple like css .Here we are making a text which is to be displayed in the window. So for that we use Label() Function. In order to make use of label function we need to call it. So we need to refer to the library first and call the object Label like this=> tk.Label() thats it .Inside this function we need to specify the window which we want this to be displayed . So for here it is window then we need to specify the text to be displayed in the window for that we use a keyword "text" so we can say our Label that the text to be displayed = the variable text. Like css we can also change the font ,font color,font size,font weight,background etc... so for that we need to use font() function in which we specify the font name , then the size of the font needed. Now fg stands for foreground which means the font color. After the function is set up we need to place it in the screen right? . Now we have made many configurations in the Label but the system now dont know where to keep it in the screen so for that we use place() function. This function allows us to place the element in almost anywhere of the screen by x y axis. We only need to specify the x and y cordinate we need them to be seen.

### L9

entry

So you have seen the input box in the output right?. Lets make it for this we use Entry() function this also needs to be called from the main library. This function return a value which is our text we are typing in it and we need to store it. So we keep it under a variable so we used w=tk.Entry here w is the variable that stores what we type. Inside the Entry() function we need to specify the window we need to display it .
then the width of the Entry field then the font like said before.

### L10

w
We need to place the entry widget in our screen so we should by giving x and y

#### Note:

Here we need to be carefull we must use w.place because of the function returning value.

### L11

button
This line is big dont worry its also simple. Here we need a button to submit it right?
For that lets call the Button() function. Inside this function we need to specify the window aswell, Then we need another function command which means same as onClick is js . This does the action when we click on the button. Actually it calls the function Display which is described in the lines L2 and L3. The next keyword is text you know what it is. Then font you know that too, Then comes the width and height here you can give the width and height of the button as integers. Then as usual we need to place it using place() function.

### L12

mainloop

mainloop() is an infinite loop used to run the application, wait for an event to occur and process the event as long as the window is not closed.
This is a loop so it needs to be repeated until we close the window thats it .

### L2

Screenshot 2020-09-19 at 11 51 33 AM
This is the function which executes when we press the submit button because we specified command = this function.

### L3

Screenshot 2020-09-19 at 11 51 47 AM
 
Now we need to print what we typed right? .For now lets print it in the terminal/CMD so we use print(then we need to get the value of w variable we defined inorder to collect the typing data.) for that we use get function.
ezgif com-gif-to-mp4
## Now you have made the simple UI.

Here is the challenge for you .WE MADE THE UI AND PRINTED THE TYPINGS IN TERMINAL .YOU NEED TO PRINT IT IN THE SCREEN ITSELF.

## Step 4: Your Custom Part

Now you know Tkinter a little bit . You should not stop here inorder to learn more and master in UIs you need to practice a lot. The best way to learn it is to look at the world and think of an idea then try to make it. You will learn Tkinter soon because its simple .

## Lastly dont stuck here i will come up with more workshops to make you know that tkinter is actually cool.
I am attaching the Tkinter documentation take a look [Learn Tkinter](https://docs.python.org/3/library/tk.html).
Also if you are new to python take a look at [python](https://www.python.org/doc/) documentation too 
### Softwares made using Tkinter by other hackers.

[Hariprasad rajan](https://repl.it/@HariprasadR03/hackthon#main.py)
[Anupriya shaji](https://repl.it/@Anupriya567/qtshb#main.py)
[kk Haridev](https://repl.it/@DandaThor/h#main.py)
[Bezlin Johnson](https://repl.it/@bezlin/graphics)

## Big platforms made using Tkinter

Billing softwares
LMS(Learning Management Softwares)
Solar Quest(Energy consemption readings)

### CODE REVIEW

**Comment by sampoder** [comment]
yo @bezlin6mechminerz mate, let me help ya out.....

Two things:

- Make your title something like `Add Tkinter Workshop`
- You shouldn't send you workshop in the PR comment, you need to make a new file in the `/workshops` folder and make it `tkinter/README.md` and then put your workshop in there

hope that helps ya out!

(ps: I had a quick read-through you might want to check your grammar... or else Grandma Grammar will come to get you!!!!)

**Comment by bezlin6mechminerz** [comment]
ok I will try

**Comment by sampoder** [comment]
you can do it!!!!!

**Comment by bezlin6mechminerz** [comment]
ok can you help me how to send workshop in the pr comment

**Comment by sampoder** [comment]
you've done that... you don't want to do that

**Comment by sampoder** [comment]
make a new file in the /workshops folder and make it tkinter/README.md

**Comment by bezlin6mechminerz** [comment]
ok

**Comment by bezlin6mechminerz** [comment]
I have created the file

**Comment by sampoder** [comment]
cool you can probs close this pr

**Comment by bezlin6mechminerz** [comment]
ok. thank you for guiding I learnt a lot GitHub today thanks brother

**Comment by sampoder** [comment]
all good :)

**Pull request closed without merging**
