### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by mj66**
The `proxyparty.hackclub.com` looks deprecated. Temporary fix is not redirect at all, basically direct imgur. Another solution would be to directly use the rawgit link, or shorten it with `hack.af`.

### CODE REVIEW

**Comment by MaxWofford** [comment]
@mj66: Wow, proxyparty isn't even set up. Thanks for finding this. Going to check our configs right now.

I'm holding off on merging because the fix for this is to get `proxyparty@hackclub.com` working.

**Comment by MaxWofford** [comment]
Looks like proxyparty.hackclub.com is good to go now

**Comment by zachlatta** [comment]
We don't want proxyparty on Hack Club's main domain. Surrogate should be live at surrogate.hackedu.us though.

________________________________

**Comment by MaxWofford** [comment]
Fixed https://github.com/hackclub/hackclub/commit/25546a6b6b6b72f5892f3d327536baeda270dca9

**Pull request closed without merging**
