### PR TITLE
added Hash Code Generator workshop

### PR DESCRIPTION
**Pull request by tanishq-soni**
Follows all the guidelines!
Also, here's the link to the meeting: https://hackclub.slack.com/files/U015MMJ6XKP/F01FUA55WNL/zoom_0.mp4
:)

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
Hey @tanishq-soni! 

Thanks for putting the effort in to create this workshop, however, I'm not so sure if we can merge this workshop without some major restructuring.

I feel like it needs MORE content tbh. It's amazing that we can make it with so little code, but the workshop reader still needs to learn something from the workshop, so maybe you could teach a bit more about what hashing is etc.

Secondly, I think that we need a product that you could actually use, rn this is really just a script but what can you do with it's output? I think it's a great opportunity for folks to learn but remember your workshop must produce a compelling, specific, real project, using real code.

Sorry, to be a bearer of bad news but I think that this will probably need a lot of work to make it mergeable.

Though, I will commend you the presentation of this workshops is pretty solid.

Thanks,

Sam

**Comment by sampoder** [comment]
Closing, feel free to reopen if you feel that you've got a product that's built on that feedback

**Comment by tanishq-soni** [comment]
sure 👍🏻, or you can accept this workshop without the bounty program? 
means i like to donate it without any bounty!

**Comment by sampoder** [comment]
I mean there's still a way of building on top of it

**Pull request closed without merging**
