### PR TITLE
SMHS CatchUp

### PR DESCRIPTION
**Pull request by saescapa**
Ok, finally PR'ing this. I wanted to do this for a long time but it has just accumulated but finally here it is. Sorry for the very long PR, hopefully it doesn't have many errors. I promised this long time ago, and sorry for keeping it for such a long time. I will be more organized, and better on time from now on.

### CODE REVIEW

**Comment by saescapa** [comment]
Also, I expected PR errors since I've been having this for a very long time.

**Comment by MaxWofford** [comment]
Wow! this is incredible @saescapa. Thanks for the contribution :D

**Comment by jonleung** [comment]
Woooo!!! Thanks @saescapa!

**Comment by jonleung** [comment]
@zachlatta and I are currently crunching pretty heavily on our tasks this week and I don't think we will have time to help merge this in. @MaxWofford, I was wondering if you happened to have time to take lead on this? No worries if not!

**Comment by saescapa** [comment]
Hey @MaxWofford what am I supposed to fix other than the links for markcop? Do I need to fix all the spelling errors?

**Comment by MaxWofford** [comment]
@saescapa Markcop now checks for spelling (and capitalization). Would you please also update your branch?

**Comment by saescapa** [comment]
Updated branch - still have some spelling errors. @MaxWofford

**Comment by saescapa** [comment]
I have updated branch again and still nothing. Is there something I'm missing?

**Comment by MaxWofford** [comment]
@saescapa Would you please fix the remaining spelling errors? https://circleci.com/gh/hackclub/hackclub/1290

**Comment by saescapa** [comment]
@MaxWofford I fixed most of them. Except for the following: 
- Codeacademy - not in dictionary
- HackGenY - not in dictionary


I also have this error: 
```case_studies/san_mateo_high_school/2015-11-04_meet_11/recap.md:8 'pdf' is spelled incorrectly!```
I believe it's because of this link (which is valid and works fine):
``` [forms](https://github.com/SMHS-Programming/club/blob/c83b49ce1e08f03f5999a5106f5e1540600328e5/documents/Feedback%20Forms/Cycle%201%20(9:14-11:4).pdf) ```

**Comment by MaxWofford** [comment]
I think the parenthesis in the filename is what is breaking the pdf link. Would you please remove them?
I believe it should be spelled "Codecademy".
HackGenY should work once https://github.com/hackclub/markcop/pull/64 is merged.

**Comment by saescapa** [comment]
All fixed!

**Comment by MaxWofford** [comment]
@saescapa Awesome! Moving to https://github.com/hackclub/hackclub/pull/662 to squash a few things.

**Pull request closed without merging**
