### PR TITLE
Chart js generator (Workshop bounty)

### PR DESCRIPTION
**Pull request by wollygfx**
@sampoder Sorry, i can't think of more hackable demos, do you have more ideas? 😪

### CODE REVIEW

**Comment by ImBIOS** [comment]
I think you can use animation with the chart. Maybe an animation when it is showed up.
Just trying to give an idea.

**Comment by sampoder** [comment]
^^ good idea

**Comment by wollygfx** [comment]
@ImBIOS Good idea, but Chart Js customization options are limited, almost non-existent... So i don't know

**Comment by wollygfx** [comment]
image
There's a big list of easing options, but i can't really notice the difference between each one

**Comment by ImBIOS** [comment]
[reference for animation in chartjs](https://www.chartjs.org/docs/master/configuration/animations/)
I will give you a reference.

```javascript
function example() {
  useEffect(() => {
    const ctx = document.getElementById('chartjs-a0').getContext('2d');
    const cfg = {
      type: 'line',
      data: {
        labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
        datasets: [{
          label: 'Looping tension',
          data: [65, 59, 80, 81, 26, 55, 40],
          fill: false,
          borderColor: 'rgb(75, 192, 192)',
        }]
      },
      options: {
          animation: {
              tension: {
                  duration: 1000,
                  easing: 'linear',
                  from: 1,
                  to: 0,
                  loop: true
              }
          },
          scales: {
            y: { // defining min and max so hiding the dataset does not change scale range
              min: 0,
              max: 100
            }
          }
      }
    };
    const chart = new Chart(ctx, cfg);
    return () => chart.destroy();
  });
  return <div className="chartjs-wrapper"><canvas id="chartjs-a0" className="chartjs"></canvas></div>;
}
```

**Review by sampoder — COMMENTED** [review]
Here are some ideas:

- Fetching data from an external API and representing it
- Making a collection of charts to tell a story
- Allowing people to publish there chart to a URL

**Pull request closed without merging**
