### PR TITLE
Promote Swiper workshop to Core

### PR DESCRIPTION
**Pull request by paked**
Congrats @zach-cmiel!

### CODE REVIEW

**Comment by MaxWofford** [comment]
Could you add the workshop to the core workshops list  up at the top of the README?

**Comment by paked** [comment]
@MaxWofford Where abouts should it go on the list?

Personally, I'm not sure that putting a workshop which requires certain technology (namely, macOS) on the "recommended" workshop path?

Maybe we could start a second list just underneath it, unordered, which is consists of core workshops you can do at any point but aren't essential? This could go there.

**Comment by MaxWofford** [comment]
@paked I like that idea. Could you change https://github.com/hackclub/hackclub/pull/914/files#diff-445fd9c7dbf08d0a1d8807caf7eac8efR21 to say something like "Workshop order"?

**Comment by paked** [comment]
I don't think it's worth bothering with the second list at the moment, there are not enough other workshops for it to be effective IMO. Besides, won't this just be a rehashing off the table just below it?

**Pull request merged**
