### PR TITLE
Replace CONTRIBUTING.md with GUIDELINES.md

### PR DESCRIPTION
**Pull request by zachlatta**
This pull request replaces our current `CONTRIBUTING.md` with the `GUIDELINES.md` document.

I don't think the old `CONTRIBUTING.md` added much information and replacing it with the `GUIDELINES.md` will be much more helpful for potential contributors.

### CODE REVIEW

**Comment by jkwok91** [comment]
https://github.com/hackclub/hackclub/pull/763/files#diff-6a3371457528722a734f3c51d9238c13L69
You don't have a GUIDELINES.md to link to anymore :wink:

**Comment by zachlatta** [comment]
Markcop is doing fine work. Will fix this.

On Thu, Mar 31, 2016 at 8:10 AM, JESSICA <notifications@github.com> wrote:

>
> https://github.com/hackclub/hackclub/pull/763/files#diff-6a3371457528722a734f3c51d9238c13L69
> You don't have a GUIDELINES.md to link to anymore [image: :wink:]
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/763#issuecomment-203980261>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Okay, just fixed. Tests should pass.

On Thu, Mar 31, 2016 at 11:48 AM, Zach Latta <zach@zachlatta.com> wrote:

> Markcop is doing fine work. Will fix this.
>
> On Thu, Mar 31, 2016 at 8:10 AM, JESSICA <notifications@github.com> wrote:
>
>>
>> https://github.com/hackclub/hackclub/pull/763/files#diff-6a3371457528722a734f3c51d9238c13L69
>> You don't have a GUIDELINES.md to link to anymore [image: :wink:]
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackclub/hackclub/pull/763#issuecomment-203980261>
>>
>
>
>
> --
> Zach Latta
> https://zachlatta.com <http://zachlatta.com>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
:tada: :tada: :tada:

On Sat, Apr 2, 2016 at 1:46 PM, JESSICA <notifications@github.com> wrote:

> Merged #763 <https://github.com/hackclub/hackclub/pull/763>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/763#event-612358662>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Pull request merged**
