### PR TITLE
Only print docker errors

### PR DESCRIPTION
**Pull request by MaxWofford**
This will remove the warning commments:

` WARNING: Your kernel does not support memory swappiness...`

### CODE REVIEW

**Comment by zachlatta** [comment]
In the tests it looks like there's still output that's not errors. Excerpt:

```
Unable to find image 'hackedu/markcop:latest' locally
latest: Pulling from hackedu/markcop












Digest: sha256:8030727d6e7d032079ef54fce7d7069edd19d47341ca272a7f7361247ab431b1
Status: Downloaded newer image for hackedu/markcop:latest
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
                                         _
                    _ __ ___   __ _ _ __| | _____ ___  _ __
                   | '_ ` _ \ / _` | '__| |/ / __/ _ \| '_ \
                   | | | | | | (_| | |  |   < (_| (_) | |_) |
                   |_| |_| |_|\__,_|_|  |_|\_\___\___/| .__/
                                                      |_|

================================================================================
                            Markcop is on patrol...
================================================================================
```

**Comment by MaxWofford** [comment]
Docker docs: 
```
-l, --log-level="debug|info|warn|error|fatal""
         Set the logging level. Default is info.
```

Me: ` $docker run -l error`

Docker: Here's a bunch of `WARNINGS`

Me: Docker >_>

Docker:

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by MaxWofford** [comment]
@zachlatta Not yet. Will work on it this week.

**Comment by zachlatta** [comment]
Any updates?

**Comment by MaxWofford** [comment]
@zachlatta No. Do you know what might be causing this?

**Comment by MaxWofford** [comment]
Closing this because it doesn't benefit us very much.

**Pull request closed without merging**
