### PR TITLE
Make Workshops Great Again

### PR DESCRIPTION
**Pull request by zachlatta**
This change thoroughly rehashes the workshops README, incorporating @sethtrei's changes in #697 and the previous workshop tracks content (though it also overhauls that).

/cc @jonleung @MaxWofford

### CODE REVIEW

**Comment by paked** [comment]
@zachlatta Looks like you have a broken link

> `workshops/CONTRIBUTING.md:59:[Community Workshops](README.md#community-workshops) 'README.md#community-workshops' is not a valid link!`

LGTM once that is resolved.

**Comment by sethtrei** [comment]
i like it except my workshop is all git and same with the github/git workshop

**Comment by zachlatta** [comment]
@sethtrei: I decided against putting a "language" for the git workshops
because git is technically a tool, not a programming language (at least in
my mind).

Perhaps we could rephrase "Languages" to "Technologies" and then put git in
it?

On Mon, Feb 8, 2016 at 2:50 PM, Seth Treiman <notifications@github.com>
wrote:

> i like it except my workshop is all git and same with the github/git
> workshop
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/699#issuecomment-181607471>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by sethtrei** [comment]
The would be perfect

**Comment by zachlatta** [comment]
Just updated!

On Mon, Feb 8, 2016 at 2:53 PM, Seth Treiman <notifications@github.com>
wrote:

> The would be perfect
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/699#issuecomment-181608905>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
This looks nice!

**Comment by sethtrei** [comment]
ready to merge?

**Comment by paked** [comment]
@sethtrei @zachlatta. Sorry this took so long.

**Comment by paked** [comment]
Good job team!

**Pull request merged**
