### PR TITLE
Mad libs Workshop (Workshop Bounty Resubmission #1)

### PR DESCRIPTION
**Pull request by JakeGerber**
I tried to make it clearer where the person following the tutorial would put the code they wrote. Let me know what you think!

### CODE REVIEW

**Comment by JakeGerber** [comment]
Resubmission from: #1461

**Review by sampoder — APPROVED** [review]
Amazing work @JakeGerber, thank you for being flexible with me! 🎉

**Review by sampoder — CHANGES_REQUESTED** [review]
View comment in #1495 :?

**Comment by sampoder** [comment]
Closing for now. Given this loads of time for changes. Putting it in the resubmission section on #1597

**Pull request closed without merging**
