### PR TITLE
D-Word Ban

### PR DESCRIPTION
**Pull request by harbar20**
No more D-Words in this Slack anymore.

### CODE REVIEW

**Comment by zachlatta** [comment]
Why? Doesn’t sound like a Code or Conduct issue to me.

**Comment by maxwofford** [comment]
Can you add some context? This doesn’t sound like an issue to me

**Comment by hkatzdev** [comment]
For context - it is a joke in the Hack Club slack community that Discord is a banned topic - it is not, this was a joke PR by @harbar20

**Comment by zachlatta** [comment]
👎 whole discussion. Also, let’s not joke about triggering people.

--
Zach Latta
https://zachlatta.com
@zachlatta / fb / github

**Pull request closed without merging**
