### PR TITLE
Adds language based section of README.md

### PR DESCRIPTION
**Pull request by sethtrei**

### CODE REVIEW

**Comment by paked** [comment]
@sethtrei I think this PR removes too much valuable information about the streams. Is there any way we could make it co-exist with the existing content?

**Comment by sethtrei** [comment]
probably but I feel that if we did, the readme would get redundant

**Comment by zachlatta** [comment]
The streams aren't really "refined" yet.

I'm for fixing the formatting in this and merging now. Then adding the
streams/tracks back later.

On Mon, Feb 8, 2016 at 1:12 PM, Seth Treiman <notifications@github.com>
wrote:

> probably but I feel that if we did, the readme would get redundant
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/697#issuecomment-181546002>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by paked** [comment]
@zachlatta Sounds good to me.

@sethtrei In order to get this merged I'm going to need to get you to fix [these errors](https://circleci.com/gh/hackclub/hackclub/1391). After that we should be good to go :)

**Pull request closed without merging**
