### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by Abubakarharuna10**
Zoom-Automation-Python

This python script signs into your zoom meetings/classes, hack night, etc on time automatically for you.
Setup instructions

Requirements: Python-3.8.6

    Clone the GitHub repo

    cd into the directory

    Install required libraries

pip3 install pandas

    Follow the instructions specific to your OS for downloading pyautogui

https://pyautogui.readthedocs.io/en/latest/install.html

    Update the timings.csv with the time of the meeting, meeting id, and password, do not add any unnecessary spaces. (Do not open the CSV using excel as it changes the formatting)

Note: Windows users

The code to open zoom is different for windows, this is shown in the main.py file make the changes accordingly.

### CODE REVIEW

**Comment by sampoder** [comment]
Hi @Abubakarharuna10 could you clarify the purpose of this at the moment?

**Comment by Abubakarharuna10** [comment]
@sampoder  yeah it's for the workshop

**Comment by sampoder** [comment]
Is this for the Workshop Bounty program?

**Comment by faisalsayed10** [comment]
Hello! I'm confused about what this PR is, also, there is not README.md file for it to be a workshop. So I'm closing it right now, feel free to reach us out if you ahve any queries.

**Pull request closed without merging**
