### PR TITLE
Revert "collab_sketch workshop clears screen on remove..."

### PR DESCRIPTION
**Pull request by ssun098**
Reverts hackclub/hackclub#854 

rip

### CODE REVIEW

**Comment by ssun098** [comment]
Reviewed by @MaxWofford in person

**Comment by zachlatta** [comment]
What happened here?

On Wed, Jun 15, 2016 at 5:31 PM, Selynna Sun <notifications@github.com>
wrote:

> Merged #855 <https://github.com/hackclub/hackclub/pull/855>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/hackclub/pull/855#event-694019021>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA8j-CWrcuDfnFyJWd-vntnpq05TSEaXks5qMJlRgaJpZM4I27A7>
> .
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by ssun098** [comment]
Accidentally merged Max's PR about live delete bc I didn't realize it
wasn't assigned to me, and he suggested that I revert it

**Comment by zachlatta** [comment]
Gotcha, just saw the other thread. :+1:

On Wed, Jun 15, 2016 at 5:43 PM, Selynna Sun <notifications@github.com>
wrote:

> Accidentally merged Max's PR about live delete bc I didn't realize it
> wasn't assigned to me, and he suggested that I revert it
>
> On Wed, Jun 15, 2016 at 5:42 PM Zach Latta <notifications@github.com>
> wrote:
>
> > What happened here?
> >
> > On Wed, Jun 15, 2016 at 5:31 PM, Selynna Sun <notifications@github.com>
> > wrote:
> >
> > > Merged #855 <https://github.com/hackclub/hackclub/pull/855>.
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/hackclub/hackclub/pull/855#event-694019021>, or
> mute
> > > the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AA8j-CWrcuDfnFyJWd-vntnpq05TSEaXks5qMJlRgaJpZM4I27A7
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Zach Latta
> > Hack Club | zach@hackclub.com
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/hackclub/hackclub/pull/855#issuecomment-226359794>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AHYhMoGFJiGmAOQWAmJ7Nt6fxH5ezkRxks5qMJvegaJpZM4I27A7
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/hackclub/pull/855#issuecomment-226360009>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA8j-ABHcVKo5gHJxs7jYx80JDyZOLWWks5qMJxOgaJpZM4I27A7>
> .
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Pull request merged**
