### PR TITLE
Fix issues brought up by @lachlanjc

### PR DESCRIPTION
**Pull request by paked**
The three points I've tried to address here are:

- Members not saving their work
- Members not knowing what the command line/terminal is
- Not knowing what the next steps to their project is

### CODE REVIEW

**Comment by paked** [comment]
@lachlanjc @MaxWofford : I'd really appreciate both of your thoughts on this. Been a while since I've written Hack Club curriculum ;)

I've ignored one of your points for now as I'd like to discuss it with the broader Hack Club team.

**Comment by MaxWofford** [comment]
@paked: This is dope! Happy to merge once the links are fixed.

**Comment by paked** [comment]
@MaxWofford: Fixed 😄

**Comment by lachlanjc** [comment]
@paked Looks great! Thanks for doing this.

**Comment by lachlanjc** [comment]
Just for reference, the feedback was in #982

**Pull request merged**
