### PR TITLE
Pac-Man Game readme.md(Resubmission #2)

### PR DESCRIPTION
**Pull request by YashKalbande**
@MatthewStanciu, I have completed all requested changes in workshop. Please review it. I think it is ready to merge.

### CODE REVIEW

**Comment by YashKalbande** [comment]
@MatthewStanciu [](https://github.com/hackclub/hackclub/pull/1439) all requested changes are done

**Comment by MatthewStanciu** [comment]
Well donee @YashKalbande! I think this is ready to merge!

One thing before I merge: can you rename the folder to `pacman` or `pacman_game`? I can't add a folder with spaces to the website. Can you also rename the file from `Readme.md` to `README.md`? Ping me on Slack once you've done it and I'll merge 🚀

**Comment by MatthewStanciu** [comment]
Awesome, thanks!

**Comment by MatthewStanciu** [comment]
I think you already filled out all the necessary payment information, so I'll get you paid asap :)

**Comment by YashKalbande** [comment]
Thank you @MatthewStanciu .

**Pull request merged**
