### PR TITLE
Change Soundboard to That Was Easy

### LINKED ISSUE #833: Improve Soundboard to inspire more exploration
Currently, Soundboard walks the user through how to place a button on their HTML page, and then connect an event handler so that when the button is clicked, a sound will be played. Then it tells the user to repeat this 15 times.

What I'm proposing is that we replace the 15 repetitions with some styling (perhaps make the button attractive and red, like the Staples "Easy" button), and let the user come up with their own ideas for how they can use this new knowledge. We'll have to flesh out the Hacking section to encourage this.

Sample hacking ideas:
- make the big red button play different sounds
- make the big red button open email client
- make the big red button close the tab
- make three different buttons, only one of which will do something (sort of like a guessing game?)

I'll build the demos for each of these hacking ideas and put screenshots in the hacking section.

### PR DESCRIPTION
**Pull request by jkwok91**
Closes #833 

TODO:
- [ ] link to the sound must be updated to be the raw mp3
- [x] a screenshot of the finished product might also be nice!

### CODE REVIEW

**Comment by zachlatta** [comment]
Wait, so should I merge as is? Or wait for you to finish those todos?

**Comment by jkwok91** [comment]
MERGE! @zachlatta

**Comment by zachlatta** [comment]
:raised_hands: 

Can you make a new issue with any remaining todos for That Was Easy?

**Comment by jkwok91** [comment]
Already made PR: https://github.com/hackclub/hackclub/pull/836

**Comment by zachlatta** [comment]
:ok_hand:

**Pull request merged**
