### PR TITLE
Updated Workshop (python-security) previous #1472

### PR DESCRIPTION
**Pull request by saneduck**

### CODE REVIEW

**Comment by MatthewStanciu** [comment]
Hey @saneduck, sorry to ask but can you tell me your @ on the Hack Club Slack? I can usually tell but in this case I can't :)

**Comment by MatthewStanciu** [comment]
Oh nevermind, I just looked at your old PR where you said your name on Slack. Sorry for the unnecessary ping!

**Comment by saneduck** [comment]
> for the unnecessary pi

It's okay! Sorry for the late response; I haven't checked my email nor this github acc for a while!

**Comment by MatthewStanciu** [comment]
Yay! Well done! This is great. I went through and made a few edits to the wording. I also went a little crazy in one section and really let me personality shine through, so I hope you don't mind lol. If you do, feel free to submit a PR to reverse it.

Congrats on getting your workshop merged! 🚀

**Pull request merged**
