### PR TITLE
Add instructions for submitting new workshop

### PR DESCRIPTION
**Pull request by jkwok91**
**Under discussion; do not merge.**

Add checklist and links to previously written guidelines.

In response to Issue https://github.com/hackclub/hackclub/issues/725.
@zachlatta: please review changes and suggest more changes.

The following words have been added to dictionary: 
- filenames
- CircleCI
- whitespace

### CODE REVIEW

**Comment by zachlatta** [comment]
Will look at when I get home from this next meeting!

**Comment by zachlatta** [comment]
Still gotta look over this, but yeah – those words should be added to Markcop.

**Comment by zachlatta** [comment]
Man, my days have really filled up unexpectedly this past week. Assigning
@remixz to handle this :-).

On Thu, Feb 18, 2016 at 3:06 PM, Zach Latta <zach@zachlatta.com> wrote:

> Will look at when I get home from this next meeting!
>
> On Feb 17, 2016, at 11:29 PM, JESSICA <notifications@github.com> wrote:
>
> *Under discussion; do not merge.*
>
> Add checklist and links to previously written guidelines.
>
> In response to Issue #725
> <https://github.com/hackclub/hackclub/issues/725>.
> @zachlatta <https://github.com/zachlatta>: please review changes and
> suggest more changes.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/hackclub/hackclub/pull/728
> Commit Summary
>
>    - Add instructions for submitting new workshop
>
> File Changes
>
>    - *M* workshops/CONTRIBUTING.md
>    <https://github.com/hackclub/hackclub/pull/728/files#diff-0> (27)
>
> Patch Links:
>
>    - https://github.com/hackclub/hackclub/pull/728.patch
>    - https://github.com/hackclub/hackclub/pull/728.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/728>.
>
>


-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by ad510** [comment]
I thought maintainers would fix markcop errors before merging so that people writing workshops don't have to worry about that? I think it is much more important for people writing workshops to focus on content than markdown formatting.

**Comment by jkwok91** [comment]
@ad510: hmm, that's an understandable concern. But this is meant as a final check, after the content has already been written. Maybe the wording could be changed to better reflect that; any ideas how?
It would also be good for contributors to understand the workshop submission workflow, which includes dealing with markcop and getting the formatting right.

**Comment by zachlatta** [comment]
>
> It would also be good for contributors to understand the workshop
> submission workflow, which includes dealing with markcop and getting the
> formatting right.
>

:+1:

Some sort of checklist for this would be nice.

 @ad510: I thought maintainers would fix markcop errors before merging so
> that people writing workshops don't have to worry about that? I think it is
> much more important for people writing workshops to focus on content than
> markdown formatting.


Yup! We're doing that for most contributions.

On Wed, Mar 2, 2016 at 1:22 PM, JESSICA <notifications@github.com> wrote:

> @ad510 <https://github.com/ad510>: hmm, that's an understandable concern.
> But this is meant as a final check, after the content has already been
> written. Maybe the wording could be changed to better reflect that; any
> ideas how?
> It would also be good for contributors to understand the workshop
> submission workflow, which includes dealing with markcop and getting the
> formatting right.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/728#issuecomment-191438126>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by remixz** [comment]
Looks good! :tada:

**Pull request merged**
