### PR TITLE
Bitcoin Price Tracker Chrome Extension (Workshop Bounty)

### PR DESCRIPTION
**Pull request by faisalsayed10**
Here's the video recording! https://hackclub.slack.com/archives/C01A9V5LPD0/p1607929273049200

### CODE REVIEW

**Comment by sampoder** [comment]
Waiting for video to do review

**Review by sampoder — CHANGES_REQUESTED** [review]
Hey Fayd! Cool workshop, here's my review (it's a video): https://hackclub.slack.com/archives/C01HW72N481/p1608719568000800

**Comment by faisalsayed10** [comment]
alright, just checked it. making the changes :+1:

**Comment by faisalsayed10** [comment]
@sampoder done! :DD

**Review by sampoder — APPROVED** [review]
speeeeeddd amazing!

**Comment by MatthewStanciu** [comment]
you're killing it

**Pull request merged**
