### PR TITLE
Add google instructions to personal website

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by jkwok91** [comment]
what about all the TODO screenshots?

**Comment by MaxWofford** [comment]
@jkwok91 I'm still working on this. I just moved it to a new branch on my own fork because I didn't have write access to @jonleung's fork.

**Comment by jkwok91** [comment]
:+1: I see!

**Comment by zachlatta** [comment]
:+1:

On Mon, Feb 15, 2016 at 12:17 PM, JESSICA <notifications@github.com> wrote:

> [image: :+1:] I see!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/718#issuecomment-184370854>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by MaxWofford** [comment]
Will get this merged by EOD.

**Comment by MaxWofford** [comment]
Merging this for the time being, will submit a PR with major changes by Thursday.

**Comment by zachlatta** [comment]
:+1:

On Mon, Feb 15, 2016 at 7:36 PM, Max Wofford <notifications@github.com>
wrote:

> Merged #718 <https://github.com/hackclub/hackclub/pull/718>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/718#event-551491921>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Pull request merged**
