### PR TITLE
Update Twilio credit card to something working

### PR DESCRIPTION
**Pull request by jonleung**
The current credit card doesn't seem to be working any longer.

### CODE REVIEW

**Comment by paked** [comment]
:+1:

**Comment by zachlatta** [comment]
Hmm, I don't think we should have Jonathan's personal contact info here.
What if he's unavailable but someone else could help?

Alternative suggestion: tell them to ping @staff in #meta on Slack.

On Wed, Feb 10, 2016 at 2:44 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/702#issuecomment-182616966>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by zachlatta** [comment]
If others are down for this change, I can submit the pull request.

On Wed, Feb 10, 2016 at 5:24 PM, Zach Latta <zach@hackclub.com> wrote:

> Hmm, I don't think we should have Jonathan's personal contact info here.
> What if he's unavailable but someone else could help?
>
> Alternative suggestion: tell them to ping @staff in #meta on Slack.
>
> On Wed, Feb 10, 2016 at 2:44 PM, Harrison Shoebridge <
> notifications@github.com> wrote:
>
>> [image: :+1:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackclub/hackclub/pull/702#issuecomment-182616966>.
>>
>
>
>
> --
> Zach Latta
> Hack Club | zach@hackclub.com
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by paked** [comment]
@zachlatta Haven't we already had this discussion (FTR: I was always against using real information...) and voted to just use correct things?

**Comment by zachlatta** [comment]
Can you clarify by what you mean by "correct things"?

I think we did also discuss this in another pull request – I don't remember
our conclusion though.

On Wed, Feb 10, 2016 at 8:03 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> @zachlatta <https://github.com/zachlatta> Haven't we already had this
> discussion (FTR: I was always against using real information...) and voted
> to just use correct things?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/702#issuecomment-182693237>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Pull request merged**
