### PR TITLE
personal_website: change "Arial" to sans-serif

### PR DESCRIPTION
**Pull request by MaxWofford**
This can't be merged yet because we have to update the gifs to reflect the change.

Blocking on https://github.com/hackclub/hackclub/issues/733

### CODE REVIEW

**Comment by zachlatta** [comment]
What's the reason behind this change again? I think it may make it a bit
less clear for people who want to customize their font – they're probably
used to seeing "Arial" where they know they can change fonts.

On Wed, Feb 24, 2016 at 9:59 AM, Max Wofford <notifications@github.com>
wrote:

> This can't be merged yet because we have to update the gifs to reflect the
> change.
>
> Blocking on #733 <https://github.com/hackclub/hackclub/issues/733>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/hackclub/hackclub/pull/736
> Commit Summary
>
>    - personal_website: change "Arial" to sans-serif
>
> File Changes
>
>    - *M* workshops/personal_website/README.md
>    <https://github.com/hackclub/hackclub/pull/736/files#diff-0> (4)
>
> Patch Links:
>
>    - https://github.com/hackclub/hackclub/pull/736.patch
>    - https://github.com/hackclub/hackclub/pull/736.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/736>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by remixz** [comment]
I proposed this change in my feedback, since I didn't want to assume that a computer had the Arial font.

@zachlatta Makes sense. We could add a section that encourages people to play with it, changing it to different fonts, like Arial, Helvetica, ~~Comic Sans~~... :smile:

**Comment by MaxWofford** [comment]
@remixz @zachlatta I'll add a section that gives people an option of fonts.

**Comment by MaxWofford** [comment]
Thoughts?

**Comment by remixz** [comment]
:+1: LGTM.

**Comment by zachlatta** [comment]
:tada: :tada: :tada:

On Wed, Feb 24, 2016 at 11:15 AM, Zach Bruggeman <notifications@github.com>
wrote:

> Merged #736 <https://github.com/hackclub/hackclub/pull/736>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/736#event-564178813>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Pull request merged**
