### PR TITLE
Add a new hack club poster

### PR DESCRIPTION
**Pull request by AppIns**
I made a poster in HTML and put it up around the school. It is fairly eye catching.

### CODE REVIEW

**Comment by MaxWofford** [comment]
@AppIns is the transparent border on purpose?

**Comment by MaxWofford** [comment]
@AppIns is the transparent border intentional?

**Comment by AppIns** [comment]
No, but it's  just an example poster

**Comment by MaxWofford** [comment]
@AppIns happy to get this merged in! Do you have the html source you used to make this? I think it'd be really useful for other club leaders to see the code and use it as a template to make their own.

**Comment by AppIns** [comment]
Yes I do but I have no idea where to put it (it's in my "Hackclub-resources"

**Comment by MaxWofford** [comment]
@AppIns: I'd create a folder called `simple_red_html_poster` and dump all the files in there.

**Comment by AppIns** [comment]
Sounds good

**Comment by AppIns** [comment]
Alright I added the source in a new directory

**Comment by MaxWofford** [comment]
Looks good! Just need you to remove the transparent border on the poster image

(this part) --> border

then I'll merge.

**Comment by AppIns** [comment]
ugh fine

**Comment by zachlatta** [comment]
This is awesome. Thanks @AppIns.

**Pull request merged**
