### PR TITLE
Create Discord.js Workshops

### PR DESCRIPTION
**Pull request by sarthaktexas**
Create a beginner-friendly discord bot tutorial that introduces beginners to Javascript. The meeting will be conducted on Monday if Zach is wondering.

### CODE REVIEW

**Comment by MatthewStanciu** [comment]
I liked the previous title. I wish I could merge it

**Comment by zachlatta** [comment]
Hey, are you still interested in trying to get this merged? Let me know so I can close if not.

**Comment by sarthaktexas** [comment]
Yep I am! Sorry for the inconvenience @zachlatta !

**Review by lachlanjc — CHANGES_REQUESTED** [review]
Hey! I’m going to close just for now since we’re trying to triage the workshops submitted, but we’d love to have this when it’s done, so feel free to re-open then.

- Could you name this something more intriguing & particular to this project? If there are multiple Discord bot workshops, they should be easily identifiable. Update the description too.
- Please add alt text to images
- I know this is WIP :) but the instructions could be a bit clearer. For example, on line 42 when you’re writing JS in a file, it should explicitly say to switch to another file & write that, etc.

**Comment by sarthaktexas** [comment]
yup i’ll do that!

**Pull request closed without merging**
