### PR TITLE
Generative Art Workshop Bounty Submission

### PR DESCRIPTION
**Pull request by ClaireBookworm**
^^^

### CODE REVIEW

**Review by lachlanjc — CHANGES_REQUESTED** [review]
Looks great! Please add the metadata before we can merge, sorry that’s not in the guidelines yet. Made a few other suggestions if you’d like to implement too.

**Comment by ClaireBookworm** [comment]
Updated! Thanks, @lachlanjc!

**Review by lachlanjc — APPROVED** [review]
Thanks!

**Comment by zachlatta** [comment]
Hey @ClaireBookworm, this is awesome! I just did a review and I think we're pretty close to merging, but I'd like a few small changes before doing my final review and then merging. Definitely qualifies for the workshop bounty upon merge.

1. For the demos at the end of the Markdown file, many club members don't have Slack. Can you convert those Slack links into direct code and live demo links? You can still have the Slack links for the examples - I'd just like something that club members who aren't on the Slack can click into. If you can't get the code and live demo links for all of them, that's OK - I'd like at least 3 that don't require a Slack account. Let me know if that makes sense.
2. Can you upload the source file of the slideshow to the #cdn channel and link it from here too? So club leaders can fork if they'd like to.
3. Can you upload a 1-2 minute video from a test session with at least 3 people per the guidelines on https://hackclub.com/workshop-bounty/? I know you ran this in a Protoclub meeting that I'm assuming wasn't recorded - if you could run another test session to get that 1-2 minute clip of what people built, that would mean this would then meet guidelines
4. Can you add a paragraph near the top explaining how the slideshow is intended to be used by club leaders? Just something giving some context to the slide show because this is a bit of a new format.

Once those 4 things are addressed, I'm ready to merge and award you the very first workshop bounty!

**Review by zachlatta — CHANGES_REQUESTED** [review]
https://github.com/hackclub/hackclub/pull/1298#issuecomment-693604398

**Comment by zachlatta** [comment]
Hey @ClaireBookworm, checking in with you on this. Are you still interested in getting this merged?

**Comment by ClaireBookworm** [comment]
Yes! I've just been a bit busy with some things, but once I get those done I'll definitely add the things you posted above! Thanks for checking in. :)

**Comment by maxwofford** [comment]
Hey @ClaireBookworm! @MatthewStanciu and I are sitting down to go through the list of pending workshop PRs & close/merge them. B/c there hasn't been any activity I'm closing it for the time being.

Once you push those changes please re-open the PR & we'll get right on reviewing it!

**Pull request closed without merging**
