### PR TITLE
Added New Workshop for Workshop Bounty discord_bot_saveMessages

### PR DESCRIPTION
**Pull request by JakeGerber**
Club meeting Showcase Video: https://hackclub.slack.com/archives/C01A9V5LPD0/p1601784167006800

Submission Requirements:
-Good Workshop Guidelines (met)
-1-2 minute video (met and link is up above)
-Assets using cdn channel (met)
-In English (met)
-Active Club member/leader (met)

Good Workshop Requirements:
-Help club members produce a compelling and real project in under 20 minutes (met. although users should be able to create a hello world discord bot as a basis to work off of)
-Are very easy to hack on for long periods of time after completion (met. users can create different features based off of saving messages. They can also use the knowledge to work on a different discord bot feature.)
-Uses replit (met. Users just have to insert their token into the bot to have it work on their end)
-Links to unknown concepts (met. I link to different concepts that the user may want more explanation on)
-Ends with at least 3 expanded demos (met.)

### CODE REVIEW

**Comment by hkatzdev** [comment]
Cool!

**Comment by Matt-Gleich** [comment]
Hey @JakeGerber! I'll review your PR as soon as I get a chance.

**Comment by Hugoyhu** [comment]
Hi @JakeGerber could you please provide a slack handle and/or a hack club you are the leader of? Thanks!

**Comment by hkatzdev** [comment]
He is a co-lead of Agoura Hack Club and his slack handle is `@Jake` :)

**Comment by Hugoyhu** [comment]
Got it, thanks. I couldn’t find him and/or I wasn’t sure whether he was an active slack member. I’m pre-reviewing everyone to see If they are like actually active or a leader.

On Oct 7, 2020, at 10:37 PM, Harrison Katz <notifications@github.com<mailto:notifications@github.com>> wrote:



He is a co-lead of Agoura Hack Club and his slack handle is @Jake :)

**Comment by MatthewStanciu** [comment]
Hey, thanks so much for submitting this! I think this is a majority of the way there, but I don't think it's quite ready to merge yet. A few things I noticed:

* At the beginning, make sure you introduce repl.it and explain how to create a project in the desired language. Although you list Hello Bot as a prerequisite, I still think every workshop should be fully explained from start to finish, as detailed as possible, which includes getting set up with repl.it
* Generally throughout, you include a lot of code snippets that move the workshop forward, but I personally found that it's very easy to get lost in the workshop, especially if the person doing it is a beginner, because the code snippets are often lacking the context of the code you wrote before it, or where you wrote the code

An example of the second point: near the beginning of the workshop, you say: "Within your client.on brackets add this if statement.

```js
if (message.content.startsWith(`${prefix}write `)) {
}
```

But an example of the same thing that would give more context to the reader:

Within your `client.on` brackets, add this if statement:

```js
client.on('message', (message) => {
  if (message.content.startsWith(`${prefix}write `)) {

  }
})
```

---

If you go through your workshop and find the spots where you feel like it could use a little more explanation or context, and make sure to explain the process of getting started with repl.it, I think it'll be ready to merge! Closing this now, but I'm looking forward to your resubmission :)

**Comment by JakeGerber** [comment]
I appreciate the feedback! I will fix it up this week and resubmit. :)

**Pull request closed without merging**
