### PR TITLE
Update GitHub pages workshop

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by MaxWofford** [comment]
@sethtrei I just went through the workshop and added a few extra descriptions. Would you care to review this?

**Comment by JevinSidhu** [comment]
Yo! I can def help out on this. @nguyenbrian and I have already worked on a guide for using gh pages!

https://hackpad.com/Basic-Git-and-Github-gOQpi30cvG8

**Comment by MaxWofford** [comment]
@JevinSidhu Thanks! Would you be interested in reviewing this?

**Comment by JevinSidhu** [comment]
@MaxWofford Definitely -- I have a few assignment from school due on *Wednesday*, but after that my week is a lot more free. I will review this then if that's cool!

**Comment by MaxWofford** [comment]
@JevinSidhu Thanks!

**Comment by zachlatta** [comment]
:+1:

**Comment by paked** [comment]
@MaxWofford I feel like these commits should follow the spec that was laid out:
https://github.com/hackclub/hackclub/blob/master/CONTRIBUTING.md#git-commits

**Comment by MaxWofford** [comment]
@paked Good point! I'll get right on it.

**Comment by MaxWofford** [comment]
Just squashed and reworded

**Comment by sethtrei** [comment]
Looks nice!

**Pull request merged**
