### PR TITLE
Vigenere cipher workshop

### PR DESCRIPTION
**Pull request by polytroper**

### CODE REVIEW

**Comment by zachlatta** [comment]
Yay! Can't wait to try this.

--
Zach Latta
Hack Club | zach@hackclub.com | Donate ( https://hackclub.com/donate )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://facebook.com/crynix ) / web ( https://zachlatta.com ) / github ( https://github.com/zachlatta )

**Comment by lachlanjc** [comment]
Awesome!! One thing—these images are pretty big, might be good to compress them. [Guetzli](https://github.com/google/guetzli) is great, I also wrote a macOS system service with Automator if you're into that.
[Resize and optimize.workflow.zip](https://github.com/hackclub/hackclub/files/2923749/Resize.and.optimize.workflow.zip)

**Comment by zachlatta** [comment]
Can we work image compression into the build process for workshops on the site so we don’t have to worry about doing this as part of development?

--
Zach Latta

https://zachlatta.com ( http://zachlatta.com )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://www.facebook.com/crynix ) / github ( https://github.com/zachlatta )

**Comment by polytroper** [comment]
Image compression in pipeline would be good. However, these images are
large mainly because they are basically videos. Would be better if we could
ref the .mp4 version like an image in markdown, and have the parser load
that as an embedded HTML5 video thing.

**Comment by polytroper** [comment]
Oh, just realized you meant the static images too. Agreed, much too large,
especially since so much bandwidth is already eaten by gifs.

For those, pipeline compression would be amazing.

**Pull request merged**
