### PR TITLE
add spanish translation for Hack Lab's workshops

### PR DESCRIPTION
**Pull request by wollygfx**
Yessirrrrr first pull request of the year 💪🏻 - Anyways, here's the description of the pr:

- Translated to spanish the 3 Hack Lab's workshops
- Added alt texts to images from some of the original workshops
- Replaced videos with gifs from the stressed ball workshop to make the workshop load faster (i noticed it was a little slow, maybe the videos were too heavy?)...

### CODE REVIEW

**Review by sampoder — APPROVED** [review]
Lets go! Thank you.

@J-cordz would you mind helping me out here and reviewing the translations? Two sets of eyes is always better then one! Thank you!

**Comment by wollygfx** [comment]
Ohhh yes please!!! I might have missed something here @J-cordz

**Review by J-cordz — APPROVED** [review]
Hi @wollygfx , I checked your changes for the translation and everything seems fine!
Thanks.

**Comment by J-cordz** [comment]
Hi @sampoder and @wollygfx. 
I reviewed the translation and it looks good!

**Comment by sampoder** [comment]
Amazing! Thanks all!

**Pull request merged**
