### PR TITLE
[META] Remove workshops made and duplicates from wishlist

### PR DESCRIPTION
**Pull request by KhushrajRathod**

### CODE REVIEW

**Comment by aaryanporwal** [comment]
We could do something like strike-through and link it, rather than removing it altogether?

**Comment by MatthewStanciu** [comment]
^ I agree with @aaryanporwal. @KhushrajRathod can you strikethrough any entries with workshops already made?

**Comment by faisalsayed10** [comment]
@KhushrajRathod you still working on this PR or may I close it (just to keep track of PRs)

**Comment by KhushrajRathod** [comment]
I'll reopen when ready 👍

**Pull request closed without merging**
