### PR TITLE
Update banners & logo in hackclub/hackclub README.md

### PR DESCRIPTION
**Pull request by ssun098**

### CODE REVIEW

**Comment by zachlatta** [comment]
Can you have this link to the latest commit instead of `master`? If people use those banner links with `master` and if we later change the location of those files, their websites will break. They won't break if we link to the latest commit SHA.

**Comment by ssun098** [comment]
Fixed!

**Comment by zachlatta** [comment]
Sweet, final thing: the new Hack Club red text logo is giant and looks super out of place in the README.

Instead of using Markdown link syntax, can you use an `img` tag to include the red text logo and set an appropriate width using the `width` attribute?

Will look something like this:

```
<img src="URL" width="400">
```

Here's what it looks like right now:

screen shot 2016-09-06 at 12 28 17 pm

**Comment by zachlatta** [comment]
Oh, and to be clear, play around with `width` until it looks right. `400` was just a filler number.

**Comment by ssun098** [comment]
Updated, could you take a look at it now? It's at 450 rn

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
Size looks good. Can you remove the commented out link and put the img tag in a header? Just precede the line with the img tag with `# `.

**Comment by zachlatta** [comment]
oh god github what have you done

**Comment by zachlatta** [comment]
oh god github what have you done

**Comment by zachlatta** [comment]
oh god github what have you done

**Comment by zachlatta** [comment]
oh god github what have you done

**Comment by zachlatta** [comment]
oh god github what have you done

**Comment by zachlatta** [comment]
oh god github what have you done

**Comment by zachlatta** [comment]
oh god github what have you done

**Comment by zachlatta** [comment]
oh god github what have you done

**Comment by zachlatta** [comment]
oh god github what have you done

**Comment by zachlatta** [comment]
oh god github what have you done

**Comment by zachlatta** [comment]
oh god github what have you done

**Comment by zachlatta** [comment]
sorry all, not sure what caused that

**Comment by zachlatta** [comment]
Assigning you while you address my most recent comment.

**Comment by ssun098** [comment]
image
@zachlatta lol same

**Pull request merged**
