### PR TITLE
Clicker game workshop

### PR DESCRIPTION
**Pull request by jasonappah**
I made a workshop on making a clicker game in React! Here's a link to the demo videos: [https://hackclub.slack.com/archives/C01A9V5LPD0/p1606745330045300](https://hackclub.slack.com/archives/C01A9V5LPD0/p1606745330045300)

### CODE REVIEW

**Review by faisalsayed10 — CHANGES_REQUESTED** [review]
Hey, just reviewed your workshop, Its great! :tada: 
But please go through this markdown file as 3-4 images are broken, so make sure u fix them

**Comment by jasonappah** [comment]
Hmm...  I tried previewing it in the 'Files changed' pane and some images didn't work, but I tried copy-pasting the Markdown from the file to [markdown.hackclub.com](https://markdown.hackclub.com/) and everything seemed to be working.

**Comment by faisalsayed10** [comment]
hmm, kinda weird

**Review by sampoder — APPROVED** [review]
Hey Jason! Great work here! Can confirm the images will render on the site, that's a weird GitHub thing.

One small request: could we make a sample application that is using `useSound` hook?

Thanks,

Sam 🚀

**Comment by jasonappah** [comment]
Just added an example of the `useSound` hook!

**Review by faisalsayed10 — APPROVED** [review]

**Pull request merged**
