### PR TITLE
Brevity, formatting and minor grammatical changes to the help_orpheus workshop

### PR DESCRIPTION
**Pull request by quackduck**
Exactly what it says in the title!
If you feel there should be any changes, please do inform me! I will gladly revert any of my changes or add new ones.

Have a great day!

### CODE REVIEW

**Comment by sampoder** [comment]
@bajpai244 could you please review?

**Comment by bajpai244** [comment]
Yeah! went throught them all fine!

**Comment by quackduck** [comment]
Maybe @sampoder means to review through the GitHub review thing?

**Review by bajpai244 — APPROVED** [review]

**Comment by sampoder** [comment]
I'll take that as an approval then

**Review by sampoder — APPROVED** [review]

**Pull request merged**
