### PR TITLE
Add C9 tutorial straight into GitHub Pages workshop

### PR DESCRIPTION
**Pull request by sethtrei**

### CODE REVIEW

**Comment by paked** [comment]
I don't think this is a good way of doing this.

**Comment by paked** [comment]
Linking out to the other workshop sounds much more ecosystem-friendly.

**Comment by MaxWofford** [comment]
@paked Would you please clarify what you mean?

**Comment by paked** [comment]
@MaxWofford @sethtrei I'm personally not a fan of redundancy. Introducing a new set of explanations in this workshop, that already exist in the Cloud9 workshop (ie. redundancy).

I think the better solution for this (as I said above) is to link directly to the Cloud9 Workshops explanations.

An example case on how this is better... Imagine the Cloud9 interface changes. We have to rewrite the workshop. If we have the same explanations here, then we have to *remember* that these workshops depend on each others content... And update it there too! In the past I have not seen this kind of workflow working well.

**Comment by sethtrei** [comment]
I like it and im willing to change it for every C9 update but ill let @zachlatta and @MaxWofford decide

**Comment by zachlatta** [comment]
While I certainly see the benefit of having this inline, I'm with @paked on this to reduce redundancy (especially since we'll be making significant refactors to our workshops in the near future).

That said, I'm 100% on board with your other changes in this pull request @sethtrei and will submit a new pull request to get those changes in :-).

Thanks for the understanding!

**Comment by sethtrei** [comment]
lol what other changes? @zachlatta

**Comment by zachlatta** [comment]
The stuff starting at https://github.com/hackclub/hackclub/pull/582/files#diff-ac1e258e1ff29351bd9080dc6c5f3570L38 and below.

**Comment by sethtrei** [comment]
sounds good!

**Comment by zachlatta** [comment]
Ah, those changes are actually already on master and made their way into this pull request because they're on this repository's master branch, but out of sync with your fork.

Can you run the following commands in your fork to update it? Warning: any changes you have on your master branch will be removed.

-------------------------------------------------------------------------------

_(remove the `$` from all of the following commands)_

Add an `upstream` remote that points to this repository. If you know you already have this set, then ignore this command.

    $ git remote add upstream https://github.com/hackclub/hackclub

Fetch the latest changes from `upstream`:

    $ git fetch upstream

Switch to your `master` branch if you're not already on it:

    $ git checkout master

Reset your `master` branch to `upstream`'s `master` branch.

    $ git reset --hard upstream/master

**Comment by zachlatta** [comment]
Also, going to go ahead and close this pull request for the time being. Sorry for deciding not to merge it for the time being @sethtrei :-(.

If you have any objections, more than happy to reopen this pull request and discuss them.

**Pull request closed without merging**
