### PR TITLE
Translation to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by gabriellimma**
Hey you, I hope you're doing well. I did this translate to PT-BR to help people of my country get into hack club. This is my first contribution on translating, but not ma last. Hope You all like.

Please fell free to contact me:
@gabriellimma
nickspoot@gmail.com

I alredy sent an e-mail to you all and this tiny contribution is one way to show my support to the hack club initiative.

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
Hey! This is certainly helpful, but we don't want to remove the English variant. Maybe you could create a separate Brazilian Portuguese file for leaders in that region.

**Comment by gabriellimma** [comment]
Hey Sam! I'm sorry, I don't have the intuition to change the version... I'll certainly try to give this translate to my country members. I really liked the Hack Club initiative, but I'm not a member... Can you help me to find my fellows country members to give them? And one more question, do you all are planning to have your site with a translate button? I'll love translate these docs to PT-BR. Thanks a lot Sam, wish you the best!

**Comment by sampoder** [comment]
You should totally join the Slack, it's best!

Re: translation, I don't think there's a plan to do that right now.

Could you make a new file at `workshops/leadership-team-br/README.md` and put you changes there?

Other than that I think I'll let @hackclub/core handle this from here :)

**Comment by gabriellimma** [comment]
@sampoder, i'm closing this PR, allready made a new onde as requested. Thank you!

https://github.com/hackclub/hackclub/pull/1645

**Comment by sampoder** [comment]
sure thing, thanks!

**Pull request closed without merging**
