### PR TITLE
Workshop: Facial Expression Recognition

### PR DESCRIPTION
**Pull request by YashKalbande**
trying to create pull request first.

### CODE REVIEW

**Comment by agarmu** [comment]
Hi Yash, I don't think it's equitable to add a pull request without a full workshop because hack club staff are worked non-stop as it is. I think you should clkse this pull request and maybe create one when you have a proper workshop ready.

**Comment by sampoder** [comment]
you can mark it as a draft pr ;) also maybe make the title a bit more descriptive

**Comment by Matt-Gleich** [comment]
Hey @YashKalbande! Excited to see what you put together here! Just changed the title of this PR as well as set it as a draft. Once you are done just ping me in this PR with @Matt-Gleich. Thank you!

**Review by Matt-Gleich — COMMENTED** [review]
Hey @YashKalbande! Please have your image files uploaded to hack club's CDN via the #cnd channel in the hack club slack.

**Comment by Matt-Gleich** [comment]
Thank you for this @YashKalbande!

One of the main objectives with hack club workshops is to start a workshop with little to no knowledge about the topic and leave with a feeling that you learning something you can apply to something else in the future. Although this goes make a good explanation of how to create a facial expression recognition model with the Teachable Machine there isn't enough material to generate a skill. In other words, this is more of a guide than a lesson.

If you would like some good examples @sampoder's workshop (#1299) and @faisalsayed10's workshop (#1300). I'm going to close this for now but please open a new PR if you think it is ready for review again.

**Pull request closed without merging**
