### PR TITLE
Updates and New Portuguese - BR translations

### PR DESCRIPTION
**Pull request by LucasHT22**

### CODE REVIEW

**Comment by grymmy** [comment]
LGTM

**Review by sampoder — APPROVED** [review]
This is great - thank you so much @LucasHT22! @adrianoapj, @LuanderFarias or @vitorvavolizza: would any of you be able to give this PR a second pair of eyes? Thanks all.

**Comment by LuanderFarias** [comment]
Nice translation @LucasHT22! Thank you so much for helping hackclub-brazil!

**Review by LuanderFarias — APPROVED** [review]
Approved my guy. Thanks again

**Comment by LucasHT22** [comment]
Thank YOU @sampoder and @LuanderFarias ! :)

**Review by adrianoapj — APPROVED** [review]
LGTM :)

**Comment by LucasHT22** [comment]
Thanks @adrianoapj !

**Pull request merged**
