### PR TITLE
Fix prehistoric typos with my SAT knowledge

### PR DESCRIPTION
**Pull request by itsmingjie**
**The me has fixed a lot of typos.**

image

### CODE REVIEW

**Comment by tmb** [comment]
looks good to me, merging when tests complete

**Comment by zachlatta** [comment]
Beat you to it 😛

**Comment by tmb** [comment]
damnit I hit the merge button and got this 
FEE REFUND 2852b73d70c4

**Comment by tmb** [comment]
damnit I hit the merge button and got this
Screen Shot 2019-06-06 at 8 03 43 PM

**Comment by itsmingjie** [comment]
I'm proud of the productivity here. The PR lasted less than 2 minutes, and 2 person reviewed it.

**Pull request merged**
