### PR TITLE
Set up CircleCI test parallelism

### PR DESCRIPTION
**Pull request by zachlatta**
Still in progress, don't merge yet.

### CODE REVIEW

**Comment by zachlatta** [comment]
Boom, test time cut in half :raised_hands:.

**Comment by zachlatta** [comment]
Alright, should be ready for merge.

This pull request enables the power of @MaxWofford's change in hackclub/markcop#96 in CircleCI, significantly cutting down our test time.

My unscientific measurements for the difference in test times:

Before this change: ~2:45 minutes
After this change: ~1:25 minutes

More than half the test time :raised_hands:.

**Comment by jkwok91** [comment]
🚋 ⭐ 🌠 🌟

**Pull request merged**
