### PR TITLE
[NOT READY FOR MERGE] add MVP playbook

### PR DESCRIPTION
**Pull request by jonleung**
_**[NOT READY FOR MERGE]**_

--

I will be sketching what I think the Playbook / Hacker Portal could look like in this pull request.

### CODE REVIEW

**Comment by MaxWofford** [comment]
@jonleung <3 Nice work making this!

What is [remind](https://github.com/jonleung/hackclub/blob/add-playbook-mvp/playbook/remind.md)?

**Comment by JevinSidhu** [comment]
@MaxWofford: Remind 101 rebranded to [Remind](https://www.remind.com)!

@jonleung This is amazing!

I would say this chart looks kind of odd with the empty 3rd space:
1. Join the Community section

**Comment by vaibhavyadaram** [comment]
@jonleung  +1 to what @JevinSidhu said about the chart. Maybe move #2 to the top right and #3 to the bottom left?

Looks dope!

**Comment by paked** [comment]
@vaibhavyadaram that would be what I would do too.

**Comment by paked** [comment]
@jonleung all the people in these gifs are white, we should strive to fix this.

**Comment by paked** [comment]
<3

**Comment by MaxWofford** [comment]
@jonleung Can we get this resolved soon? I'd like it to either be closed or merged so we don't have a  backlog of PRs.

**Comment by zachlatta** [comment]
:+1: to @MaxWofford's comment

On Sun, Jan 10, 2016 at 3:54 AM, Max Wofford <notifications@github.com>
wrote:

> @jonleung <https://github.com/jonleung> Can we get this resolved soon?
> I'd like it to either be closed or merged so we don't have a backlog of PRs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/600#issuecomment-170338065>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.io

**Comment by jonleung** [comment]
Let's close it! Thanks!

**Pull request closed without merging**
