### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by jonleung**
Adding our code of conduct that @paked and I worked on together!

@hellyeah, would love any feedback that you have on this!

### CODE REVIEW

**Comment by jonleung** [comment]
@zachlatta sorry for the assignment, it's not ready to merge yet but I'll assign you back when it's ready!

**Comment by jonleung** [comment]
@zachlatta, ok, this should be good to merge!

**Comment by jonleung** [comment]
This moves one step closer to completing #117

**Comment by jonleung** [comment]
Actually, assigning @MaxWofford instead because @zachlatta is very busy right now!

**Comment by paked** [comment]
GOOD JOB T34M

**Pull request merged**
