### PR TITLE
add dashboard project

### PR DESCRIPTION
**Pull request by samayshamdasani**
a workshop centered all around APIs that fetches data such as weather and news

### CODE REVIEW

**Comment by samayshamdasani** [comment]
also, hack club needs to get obtain it's own API keys from https://darksky.net/dev/ & https://newsapi.org

**Comment by ItsDaGeek** [comment]
*Assigned to review and verify*

**Comment by zachlatta** [comment]
Markcop, where are you?

**Comment by zachlatta** [comment]
Just ran Markcop locally and everything seems to pass after that latest commit.

**Comment by zachlatta** [comment]
@ItsDaGeek: let me know once you have a chance to give this a deeper review. Waiting on your green light before merging.

**Comment by ItsDaGeek** [comment]
Been traveling all day. Will be able to look at it soon. I will be able to say by EOD Wednesday

**Pull request merged**
