### PR TITLE
Submitting workshop to hackedu

### PR DESCRIPTION
**Pull request by sethtrei**
I made a workshop that teaches scholars how to create a GitHub Pages website. 
Note: The feedback currently goes to my personal feedback form. If this gets accepted, I or someone else will switch the feedback to a hackclub form.
Thanks.

### CODE REVIEW

**Comment by zachlatta** [comment]
Hey @sethtrei! Thank you for the pull request.

It looks like the commit submitted is from a submodule. Can you make sure the commits in this pull request contain your full changes?

Let me know if you have any questions getting all of your changes added. Happy to help :-).

**Comment by zachlatta** [comment]
I ended up finding https://github.com/sethtrei/githubpages, which I assume is the workshop in question. I took your changes from that and put them in a pull request over in #510, which I just merged (you'll still get credit for the change on GitHub :-).

Thank you for the workshop! And congratulations on your first contribution.

**Comment by paked** [comment]
@zachlatta your gif game just `LEVEL UP`d!

**Comment by sethtrei** [comment]
:+1:

**Comment by MaxWofford** [comment]
Thanks for the pull request @sethtrei!

Here's a picture trying and failing to submit a contribution because it's arms are too small:

contributing_dinosaur

**Comment by sethtrei** [comment]
lol that's great

**Comment by zachlatta** [comment]
https://github.com/hackclub/dinosaurs/blob/20ed87ef9e4b6331ec3a55bf191a48c28375c1b5/dino_winning.png

**Comment by sethtrei** [comment]
These should be in a museum

**Comment by prophetorpheus** [comment]
In fact... https://github.com/hackclub/dinosaurs

**Pull request closed without merging**
