### PR TITLE
Add note on using Excel/Google Sheets for sign-ups

### PR DESCRIPTION
**Pull request by zachlatta**

### CODE REVIEW

**Comment by zachlatta** [comment]
Decided to re-assign to @MaxWofford because I'm currently waiting on @jonleung for other pull requests.

**Comment by ad510** [comment]
I got this! One moment...

**Comment by ad510** [comment]
I think something like this would be clearer:

Excel or Google Sheets is a good way to collect this info, though it's a good idea to also bring a pencil and a clipboard in case of technical difficulties.

**Comment by zachlatta** [comment]
Good call, changing now!

On Mon, Jan 18, 2016 at 10:16 AM, Andrew Downing <notifications@github.com>
wrote:

> I think something like this would be clearer:
>
> Excel or Google Sheets is a good way to collect this info, though it's a
> good idea to also bring a pencil and a clipboard in case of technical
> difficulties.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/659#issuecomment-172610923>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Just changed in most recent push.

On Mon, Jan 18, 2016 at 10:16 AM, Zach Latta <zach@zachlatta.com> wrote:

> Good call, changing now!
>
> On Mon, Jan 18, 2016 at 10:16 AM, Andrew Downing <notifications@github.com
> > wrote:
>
>> I think something like this would be clearer:
>>
>> Excel or Google Sheets is a good way to collect this info, though it's a
>> good idea to also bring a pencil and a clipboard in case of technical
>> difficulties.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackclub/hackclub/pull/659#issuecomment-172610923>.
>>
>
>
>
> --
> Zach Latta
> https://zachlatta.com <http://zachlatta.com>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
I'm a pull request, look at me!

**Pull request merged**
