### PR TITLE
Reorder steps in Github pages workshop

### PR DESCRIPTION
**Pull request by sethtrei**
I want to reorder the cd [repo] part of the workshop

### CODE REVIEW

**Comment by sethtrei** [comment]
Note: I did my personal commit differently then your guys' format. I didnt think it would stay there when I did the pull request.

**Comment by paked** [comment]
@sethtrei I'm going to fix your commit message and then merge it in :) Thanks for the contribution!

**Comment by paked** [comment]
Closed in favour of #570

**Comment by zachlatta** [comment]
<3

Thank you @sethtrei. This is awesome.

**Pull request closed without merging**
