### PR TITLE
Scalable Snowman Workshop (Workshop Bounty)

### PR DESCRIPTION
**Pull request by JakeGerber**
Club meeting Showcase Video: https://hackclub.slack.com/archives/C01A9V5LPD0/p1606423506042400

Submission Requirements:
-Good Workshop Guidelines (met)
-1-2 minute video (met and link is up above)
-Assets using cdn channel (met)
-In English (met)
-Active Club member/leader (met)

Good Workshop Requirements:
-Help club members produce a compelling and real project in under 20 minutes (met)
-Are very easy to hack on for long periods of time after completion (met. can add new colors, randomized sizes, more objects, etc.)
-Uses replit (met)
-Links to unknown concepts (met)
-Ends with at least 3 expanded demos (met.)

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
Hey @JakeGerber! 

Thanks for submitting another workshop! My primary concern is that we've got a couple of workshops quite similar to this. Mainly: https://workshops.hackclub.com/py_christmas/.

Could you work on differentiating this workshop from this current one?

Thanks,

Sam 🚀

**Comment by JakeGerber** [comment]
> Hey @JakeGerber!
> 
> Thanks for submitting another workshop! My primary concern is that we've got a couple of workshops quite similar to this. Mainly: https://workshops.hackclub.com/py_christmas/.
> 
> Could you work on differentiating this workshop from this current one?
> 
> Thanks,
> 
> Sam 🚀

Hey so mine has the snowman parts (eyes and nose) scale and change placement depending on the radii that the user inputs which I think is pretty different. I could probably add another element like random snow placement on the screen if that would help differentiate it more though. Would that sound ok?

**Comment by sampoder** [comment]
Hmmm, would there be any way of adding user input?

**Comment by JakeGerber** [comment]
Yeah I could try adding that so you could have them move left and right. Would I have to have another club meeting video for it?

**Comment by sampoder** [comment]
that sounds cool! probs not (@MatthewStanciu?)

**Pull request closed without merging**
