### PR TITLE
Guidelines on politics in the COC

### PR DESCRIPTION
**Pull request by jacobhaap**
The code of conduct needs to specify where political activity is to take place and to clarify that any one group will never be silenced unless absolutely necessary.

### CODE REVIEW

**Comment by lachlanjc** [comment]
I think the language here is too vague to be useful or enforceable. My posting a picture of myself with makeup on in #lounge is a political statement—where does that go? The existence of #orpheus-legion is rooted in feminism, which is a political statement. & if political language can only be in designated channels, does that mean you can’t set your status to BLM? Etc, etc. I think we shouldn’t police “political language” specifically because, as Twitter is finding out with “no political ads,” there are infinitely-grey boundaries to what is political, & instead address handling situations related to politics via the rest of the COC.

**Comment by jacobhaap** [comment]
Thank you for the quick feedback!  I do have some additional questions to help me understand, and it is my hope these will not be interpreted as disrespectful as such is not my intent.

If we shouldn't police "political language," does that mean a hypothetical member (like Elon Musk) could say they are tired of "pronouns"?  Is it okay for autistic members to use words like "reeee" without being told they are making fun of autistic people (such as Garrett)?  Is it okay for non-POCs to attack POCs for being racist against POCs?

It is starting to feel like this space is protected for left-authoritarians, but if anyone is a left-libertarian or conservative, voices get shut down.  I think of this group as an inclusive space for people of different backgrounds to come together because of their love of coding and making things, and I'd hate to think we start excluding large sections of people to accommodate, one group.

**Comment by jacobhaap** [comment]
I would also like to add that if possible to move forward with incorporating guidelines on political activity within the Code of Conduct, I think it would be beneficial to have more community involvement with it, especially for fixing the vague language you described.

**Comment by MatthewStanciu** [comment]
I totally agree that Hack Club has a politics problem, but I don’t believe adding this section to the code of conduct will have the effect you want it to have. I think that instead of making the Slack a place where people can freely be who they are and express themselves however they want, Hack Club committing to “never silencing” political beliefs on Slack would actually open the door to protecting all sorts of hateful and hurtful comments that happen to contain a political statement, because the people making those comments could object to moderation action by claiming their political beliefs are being silenced, even if the moderation action was unrelated to the political beliefs they expressed.

If someone came into Slack and said “pronouns suck”, I would remove that message, not because of their opinions on pronouns, but because expressing that opinion in that way is both unproductive to any discussion and makes many queer people in the community feel less safe on the Slack. A recent example of something like this happening is @purple (Vitaliy Kuzhdin) responding to a Scrapbook post someone made about a Girls Who Code checkin call with “why is there girls who code but not boys who code?” and arguing with people in the thread. Comments like his should absolutely not be welcome in the community, not because of his opinion on girls who code, but because he chose to express it in an unproductive and inflammatory manner on a totally unrelated Scrapbook post. Another hypothetical example of something like this would be someone randomly commenting “ACAB” on a Scrapbook post about someone spending time with a family member who happens to be a police officer.

Restricting political statements to certain spaces does more harm than good because of what Lachlan said re: infinite gray areas, and committing to “not silencing” political opinions effectively serves as an uno reverse card that people who made legitimately unwelcome comments can use anytime we moderate their comments. This is why I believe political statements are the wrong things to focus on, and fixing our “politics problem” starts with focusing on **hurtful, unproductive comments** rather than political statements.

I’m going to close this, but if you want to discuss further, including other ways we can work on making the Slack a safe place for everyone, just reply to this or DM me ✌️

**Pull request closed without merging**
