### PR TITLE
Image_Editor workshop patches.

### PR DESCRIPTION
**Pull request by alialiwa2005**
- Added missing ```<script src="script.js"></script>``` in HTML5 code.
- Fixed missing range error by replacing ``inputrange``` with ```inputRange``` in JavaScript code.
- Removed ```<details>```, because it may have been the cause of critical display errors on the workshop page.

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
I'd prefer to keep the details. It keeps the workshop condense.

**Comment by alialiwa2005** [comment]
Okay.

**Comment by alialiwa2005** [comment]
I'll add them back.

**Review by alialiwa2005 — COMMENTED** [review]
```<details>``` tags have been added back.

**Comment by wollygfx** [comment]
@alialiwa2005 Thanks for helping out, don't know why i missed all these things

**Comment by MatthewStanciu** [comment]
Thanks 🙌 🚀

**Comment by alialiwa2005** [comment]
> @alialiwa2005 Thanks for helping out, don't know why i missed all these things



> Thanks 🙌 🚀

You're welcome!

**Pull request merged**
