### PR TITLE
Workshop - Figma for beginners

### PR DESCRIPTION
**Pull request by PavithSudhirAP**
Hackclub workshop bounty:
Topic: Figma for beginners

Timelapse of the workshop i conducted :
https://hackclub.slack.com/files/UG60Z8MUK/F01AP1AJ4BY/figma4beginners.mp4

### CODE REVIEW

**Comment by sampoder** [comment]
View https://hackclub.slack.com/archives/C0C78SG9L/p1600175537137800?thread_ts=1600139473.124400&cid=C0C78SG9L

**Comment by PavithSudhirAP** [comment]
Hi, this is actually a re-submission of my workshop. Last time my PR was closed by @zachlatta due to grammar errors.

**Comment by sampoder** [comment]
Hey @PavithSudhirAP, just for some housekeeping work on my end, what hack club do you lead?

**Comment by PavithSudhirAP** [comment]
> Hey @PavithSudhirAP, just for some housekeeping work on my end, what hack club do you lead?

I am a member of COET coding club, lead by Annlee Fores.

**Comment by Matt-Gleich** [comment]
Hey @PavithSudhirAP! Is this ready for review and have you read [the workshop bounty requirements](https://workshops.hackclub.com/workshop-bounty/)?

**Comment by PavithSudhirAP** [comment]
> Hey @PavithSudhirAP! Is this ready for review and have you read [the workshop bounty requirements](https://workshops.hackclub.com/workshop-bounty/)?

yes

**Comment by sampoder** [comment]
@Matt-Gleich are non code workshops allowed? I was under the impression they weren't

**Comment by Matt-Gleich** [comment]
@sampoder let me check with zach.

**Comment by Hugoyhu** [comment]
Hi @PavithSudhirAP could you please provide a name of the Hack Club you lead? Thanks!

**Comment by PavithSudhirAP** [comment]
> Hi @PavithSudhirAP could you please provide a name of the Hack Club you lead? Thanks!

I am a member of  COET coding club, in Kerala, India.

**Comment by lachlanjc** [comment]
Hey! I'm so sorry there's been so much back-&-forth without good news here, I know that's not a great experience, but we can't accept this workshop for the bounty. You must be a club leader or active Slack member to submit, & workshops must be about coding.

**Pull request closed without merging**
