### PR TITLE
BMI application using app inventor

### PR DESCRIPTION
**Pull request by chrisrama**

### CODE REVIEW

**Comment by chrisrama** [comment]
I am done with everything except for the last what can a person do more

**Review by lachlanjc — CHANGES_REQUESTED** [review]
Hey there! Thanks for your submission.

On your App Inventor workshop just with a cursory glance, it does not meet a number of our guidelines. The images are missing alt text, there are several obvious Markdown formatting issues (see line 159), quite a number of spelling & punctuation issues (including the description), but larger than formatting, I don't see code blocks—workshops must deal with technical concepts through writing code, not only visual editors.

I haven't looked through the second workshop extensively but it has a number of formatting/syntax issues as well, a lack of visuals, code formatting, 3 hacks/creative directions at the end, & your PR is lacking the demo videos required.

I'm going to close this for now but when you've got your workshops meeting all our guidelines, we'd love to take another look. Please open a PR for each workshop too. Thanks!

**Comment by chrisrama** [comment]
@lachlanjc what does resubmission-requested mean?

**Comment by lachlanjc** [comment]
That means we'd be happy to review another PR, but this needs major changes before resubmitting to be in line with the bounty requirements.

**Comment by chrisrama** [comment]
oh sorry @lachlanjc , I didn't see your comment before. so I will try to fix the BMI application soon, then for the other workshop I will delete it, my friend was doing that under my name, I told him of the same issues of the visualization, but he thinks it won't be necessary. so before I resubmit I will just ask for a review if it okay, then the for video demo, I am doing it with my friend and it should be ready soon.

**Comment by chrisrama** [comment]
what you meant by missing alt text, is it the text for the image right?

**Comment by lachlanjc** [comment]
Ok great! Sounds good. Yep, alt text is the image descriptions/captions.

**Comment by chrisrama** [comment]
"I don't see code blocks—workshops must deal with technical concepts through writing code, not only visual editors." hey @lachlanjc I saw you mention this, what I actually did was through the text I provide the code block that is being used then provide also a picture of how it looks, Is this what you were trying to tell me.

**Comment by lachlanjc** [comment]
Yeah, so to clarify, you can't use visual editors like App Inventor for Hack Club workshops—workshops must use regular code in an environment like replit, Glitch, etc.

**Comment by chrisrama** [comment]
so that means should I continue😬

**Comment by lachlanjc** [comment]
You’re welcome to change the workshop to use code & resubmit, but using code is one of the bounty guidelines

**Comment by chrisrama** [comment]
@lachlanjc can You reopen the pull request pls and see what I did now.

**Pull request closed without merging**
