### PR TITLE
Alt text to images in workshops

### PR DESCRIPTION
**Pull request by giridhar7632**
This pull request closes the issue #1263

### CODE REVIEW

**Review by KhushrajRathod — CHANGES_REQUESTED** [review]
Cool -- One thing to note is that the alt text is for humans to read and doesn't need to be machine readable -- Spaces are better as compared to underscores and hyphens

**Review by KhushrajRathod — CHANGES_REQUESTED** [review]
Also I just realized that the alt text you've input is just the file name -- Alt text needs to be a full description of the image

**Comment by MatthewStanciu** [comment]
Wow, thank you so much for this @giridhar7632!

I agree with @KhushrajRathod's suggestions—the point of alt text is for humans who use screen readers or can't load the images to be able to understand what's in the image, so it would actually be more beneficial if the alt text contained spaces and were a little more descriptive. Could you make those changes? Then I'd love to get this merged.

Let me know if I can be helpful 🙌

**Comment by giridhar7632** [comment]
I changed the names more like for humans 😅

**Review by KhushrajRathod — CHANGES_REQUESTED** [review]
Hey, Awesome work 🚀 
Still needs a lot of changes though. I feel like the thing missing here is that the alt text isn't for people who can see the images. Imagine being blind (or go to the "changed files" on the PR where images don't load) and see if you can understand what the images look like just by reading the alt text -- that's what the alt text is for. I've reviewed some of the files as an example of what's missing --

**Comment by isa3bel** [comment]
Is this still unresolved?

**Comment by sampoder** [comment]
Yes

**Comment by isa3bel** [comment]
do I need to fork the repo to add changes or can I just clone it? @sampoder

**Comment by sampoder** [comment]
probably fork it

**Pull request closed without merging**
