### PR TITLE
Add Final Code and Live Demo links

### PR DESCRIPTION
**Pull request by JSneak**
Not sure about this one. I'm hosting both on my github page and I don't know if that is a problem or not.

### CODE REVIEW

**Comment by JSneak** [comment]
If this is fine, I have a live demo for the animated Geometric Pattern that gets rid of the text that doesn't work. I could also add an actually working live demo for the Collaborative Sketch one. The current one restrict people from editing or deleting.

**Comment by MaxWofford** [comment]
@JSneak I just updated it to have a similar format to the other workshop READMEs.

**Comment by MaxWofford** [comment]
I can put https://github.com/JSneak/jsneak.github.io/tree/master/dawgshop onto https://github.com/prophetorpheus if you want.

**Comment by MaxWofford** [comment]
nvm that last comment. Could you submit a PR to https://github.com/prophetorpheus/prophetorpheus.github.io with the code for the dawg it project?

**Comment by JSneak** [comment]
Done @MaxWofford . Also changed the links to go to Prophet Orpheus

**Pull request merged**
