### PR TITLE
"Leadership Team" Translation to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by gabriellimma**
Created a new folder as requested 😄 

This PR relates to:  https://github.com/hackclub/hackclub/pull/1644 

Thx for all the support @sampoder.

I'm trying to enter the slack community, but I think isn't possible now... Do you have any information about that?

### CODE REVIEW

**Comment by sampoder** [comment]
thanks! leaving this to core team from here, glad I could help!

**Comment by sampoder** [comment]
Oh right also @gabriellimma, do you want access to the Hack Club Slack? If so just drop me a line at @ sam-gh@sampoder.com. Thanks!

**Comment by gabriellimma** [comment]
> 
> 
> Oh right also @gabriellimma, do you want access to the Hack Club Slack? If so just drop me a line at @ [sam-gh@sampoder.com](mailto:sam-gh@sampoder.com). Thanks!

Done @sampoder , thank you for all the support!

**Comment by MatthewStanciu** [comment]
Wow, thanks so much! And welcome to the community :)

**Pull request merged**
