### PR TITLE
Drum Pad (#Resubmission)

### PR DESCRIPTION
**Pull request by emmanuel39hanks**
Criteria:

> **Criteria:**
> 
> * [x]  Workshop that meets all of the "Good workshops" guidelines outlined above (View below)
> * [x]  1-2 minute video clip from your test club meeting showing what members built (View: https://slack-files.com/T0266FRGM-F01BGHMCSR0-d76af4939e)
> * [x]  All assets (images, PDFs, and any other binaries) must be hosted using the #cdn channel on the Hack Club Slack for posterity and to cut down on repository size
> * [x]  All workshops must be in English at native-level proficiency. Phrasing and grammar must be perfect.
> * [x]  You must be either a registered Hack Club leader or an active member of the Slack (I am a club leader, and I also count as an active member in the community, I hope)
> 
> **Good workshops guidelines:**
> 
> Help club members produce a compelling and real project in under 20 minutes
> 
> > This workshop can be completed in under 20 minutes, based on the test meeting. I would define this as a compelling project as it is something they can show off and it is very visual. It is a real project as they will be using HTML, CSS & jQuery to make a beatmaker/drum pad.
> 
> Are very easy to hack on for long periods of time after completion
> 
> > Yes, during the test meeting only people found it interesting and wanting to add more functionality like recording etc. And having future plans with the project.
> 
> Have instructive and compelling images, GIFs, and visuals
> 
> > It does have them.
> 
> Use repl.it or a similar service that allows members to begin coding with one click
> 
> > Yes.
> 
> Link unknown concepts to external sources.
> Yes, I have linked docs and unknown sources.
> > It relates CSS animation keyframing to video animation keyframing and relates CSS variables to how variables in other languages.
> 
> End with at least 3 demos of how the project can be expanded, with live links and code links for each demo.
> 
> > Yes, it has 3 expansions on the project with live links code links.
> 
> Please let me know if I missed anything, and feel free to improve it.

### CODE REVIEW

**Comment by emmanuel39hanks** [comment]
@sampoder, I feel it is ready to review, thanks for pointing out that I was adding code to link the other files but it was already there.

**Review by JayantGoel001 — APPROVED** [review]

**Comment by emmanuel39hanks** [comment]
@JayantGoel001 Thanks for approving my changes. 
@MatthewStanciu Can you have a final check?

**Comment by sampoder** [comment]
shoot that was an accident

**Comment by sampoder** [comment]
i meant to approve

**Pull request merged**
