### PR TITLE
Add step to share personal website on #shipit

### PR DESCRIPTION
**Pull request by jkwok91**

### CODE REVIEW

**Comment by MaxWofford** [comment]
This is waiting for https://github.com/hackclub/markcop/pull/75

**Comment by zachlatta** [comment]
In other places we just put the channel name in backticks to get it to render as inline code, which Markcop ignores (ex. `#shipit`). What if we did that here?

**Comment by MaxWofford** [comment]
@zachlatta Cool with that. I'd prefer it to remain linked to though.

/cc @jkwok91

**Comment by jkwok91** [comment]
got it

**Comment by MaxWofford** [comment]
Cool! Going to merge it!

**Comment by jkwok91** [comment]
:clap: :crown:

**Pull request merged**
