### PR TITLE
Update sound link

### PR DESCRIPTION
**Pull request by jkwok91**
Remaining TODO for https://github.com/hackclub/hackclub/pull/835

### CODE REVIEW

**Comment by zachlatta** [comment]
Err, actually not sure how I feel about this. If we ever change the name of that sound, Markcop won't catch the broken link and we could be linking people to a 404.

How bad is it if we tell them to click the "Raw" button?

**Comment by jkwok91** [comment]
I was thinking that since we ran into so many issues with people
accidentally somehow saving the mp3 as an html, it would be better to shave
off unnecessary steps.

**Comment by zachlatta** [comment]
So you think it's worth the tradeoff?

**Comment by jkwok91** [comment]
This has been updated; check now.

**Comment by zachlatta** [comment]
Looking good, but now there are merge conflicts. Will merge after they're resolved.

**Comment by jkwok91** [comment]
<3

**Pull request merged**
