### PR TITLE
Chart generator (Workshopt bounty)

### PR DESCRIPTION
**Pull request by wollygfx**

### CODE REVIEW

**Comment by wollygfx** [comment]
@sampoder Here you have the resubmission of [this pull request](https://github.com/hackclub/hackclub/pull/1453)

**Review by sampoder — CHANGES_REQUESTED** [review]
Great work here! Could you work on getting 3 hackable demos?

**Comment by sampoder** [comment]
Meanwhile, I'll make some small grammar fixes

**Comment by sampoder** [comment]
closing for now, excited for the resubmission!

**Pull request closed without merging**
