### PR TITLE
Add new GIFs

### PR DESCRIPTION
**Pull request by eilla1**
I updated CONTRIBUTING.md to use GIFs that reflect the new GitHub interface. Let me know if I should make any changes to the GIFs!

### CODE REVIEW

**Review by KhushrajRathod — CHANGES_REQUESTED** [review]
Yay! New gifs.
Could you remove the old ones from the img directory?

**Comment by KhushrajRathod** [comment]
?

**Comment by eilla1** [comment]
I renamed the branch and it closed itself 🤔

**Comment by KhushrajRathod** [comment]
Hm

**Comment by eilla1** [comment]
it's now at [hackclub/hackclub#1703](https://github.com/hackclub/hackclub/pull/1703)

**Pull request closed without merging**
