### PR TITLE
sort workshops

### PR DESCRIPTION
**Pull request by sethtrei**

### CODE REVIEW

**Comment by paked** [comment]
This is quite a big change, we need to have a discussion before merging. I personally am quite worried about breaking existing links from external resources.

I think a better place to implement this sorting would be directly in the [README.md](https://github.com/hackclub/hackclub/blob/master/workshops/README.md) file itself.  We could add some sort of difficulty column, and use the unicode [★](http://www.fileformat.info/info/unicode/char/2605/index.htm) to create a rating system?

cc: @zachlatta @MaxWofford @jonleung

**Comment by sethtrei** [comment]
I understand it is big. But it makes finding the proper workshop much easier. If youre new, it can be tough to find what you're looking for. Say someone wants to learn JavaScript. Instead of going through each workshop, they can just go to the JavaScript folder.

**Comment by paked** [comment]
I think however that we could have the exact same effect by modifying the existing table structure in the README.

Do we even show club members the raw GH folder page? I thought we always linked to the README anyway.

**Comment by sethtrei** [comment]
You are correct with the link to the README. But if your club said "choose your own path on Hackclub" then they will see the folders

**Comment by paked** [comment]
Whenever I have said "explore Hack Club", I give my members a link to the main workshops README and let them navigate around from there.

**Comment by jonleung** [comment]
Thanks for the thoughtful pull request @sethtrei!

I totally see the problem of it being difficult to find workshops if you don't necessarily know what you're looking for. Your comment:

> makes finding the proper workshop much easier. If youre new, it can be tough to find what you're looking for. Say someone wants to learn JavaScript. Instead of going through each workshop, they can just go to the JavaScript folder.

**really** resonates with me.

At the same time, I agree with @paked on the following points:

> - I personally am quite worried about breaking existing links from external resources.
> - I think however that we could have the exact same effect by modifying the existing table structure in the README.

Moreover, I think the flat structure of workshops (all workshops being in the root directory) is more robust and scalable for the future. I can imagine that we have many different categories and a given workshop can fit into two categories and it will be hard to figure out which folder to put things in.

So I'm leaning towards figuring out some solution to this problem via modification of the `README.md`.

Also, @sethrei, could you elaborate on this comment:

> But if your club said "choose your own path on Hackclub" then they will see the folders

I'm not quite sure what you mean.

**Comment by sethtrei** [comment]
Yea. So with my club for the first few weeks, the leaders told us which workshops to do each week. Eventually they stopped doing that every meeting (which I was fine with). So when they stopped giving me links, I had to go through the workshops folder myself. Harrison said how he gives member links to the readme but not every club does that.

**Comment by jonleung** [comment]
@sethtrei, suppose that every club gave links to `workshops/README.md`, do you think that solve the problem?

**Comment by sethtrei** [comment]
Yes, however like I said, not every club does that and I know that I at least (and im sure other people also) like to work on hackclub at home and will do it without the club. While working alone, they may want to get ahead so then they will see these folders. Also you said that the option with all the workshops together is more scaleable. I disagree with this as if we add workshops eventually it will just be a giant list of workshops(and that would just not be good). I think they need categories and we can just add them as they are necessary.

**Comment by zachlatta** [comment]
I'm for sorting and linking to the workshops from the README. It'll easily
allow us re-sort workshops in the future and provides a consistent linking
scheme (you know a workshop will always be in `workshops/[workshop_name]`).

@sethtrei: if the README of the workshops directory was shorter and began
with a super quick bullet point list for categories of workshops, would you
use it?

On Wed, Feb 3, 2016 at 3:57 PM, Seth Treiman <notifications@github.com>
wrote:

> Yes, however like I said, not every club does that and I know that I at
> least (and im sure other people also) like to work on hackclub at home and
> will do it without the club. While working alone, they may want to get
> ahead so then they will see these folders. Also you said that the option
> with all the workshops together is more scaleable. I disagree with this as
> if we add workshops eventually it will just be a giant list of
> workshops(and that would just not be good). I think they need categories
> and we can just add them as they are necessary.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/688#issuecomment-179540150>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by sethtrei** [comment]
probably but again I am really advocating for my idea and people would more likely click on the workshops folder instead of reading. but idk I could just be biased lol

**Comment by zachlatta** [comment]
I definitely see why it'd be easier to click through the sorted workshop
folders, but I'm primarily worried that it increases the barrier to finding
the workshops (right now you know that it's always going to be in
`workshops/[name]`) and it further complicates our directory structure.

On Wed, Feb 3, 2016 at 7:22 PM, Seth Treiman <notifications@github.com>
wrote:

> probably but again I am really advocating for my idea and people would
> more likely click on the workshops folder instead of reading. but idk I
> could just be biased lol
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/688#issuecomment-179595626>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by paked** [comment]
I think this whole argument can be distilled to the fact that clubs are distributing our workshops as the link to the GitHub folder instead of the README.

We could solve this problem in an equivalent manner but without the side effects by setting the precedent that every time a club member is asked to navigate around a Hack Club resource they use the file view.

However, I do agree that we should allow some sort of sorting around the language and difficulty. But again, please can we put this in the README?

**Comment by sethtrei** [comment]
Sure, I think that would be a good compromise.

**Comment by jonleung** [comment]
@sethtrei, would you be interested in making a pass at what that `README.md` would look like?

**Comment by sethtrei** [comment]
yes but two things
1.What do you mean by pass?
2. sure but I wont be able to do it that soon. Maybe like 2 days.

**Comment by jonleung** [comment]
Ah, sorry about confusion. By "pass", I mean "attempt":

> @sethtrei, would you be interested in making an _**attempt**_ at what that README.md would look like?

In ~2 days sounds good!

**Comment by sethtrei** [comment]
So I was about to work on it but it is basically already there at https://github.com/hackclub/hackclub/blob/master/workshops/README.md 
All we would have to do is update it.

**Comment by zachlatta** [comment]
How would you recommend updating it? It'd be awesome for you to make that
change (though I'm happy to as well if you'd prefer I did).

On Sun, Feb 7, 2016 at 7:59 AM, Seth Treiman <notifications@github.com>
wrote:

> So I was about to work on it but it is basically already there at
> https://github.com/hackclub/hackclub/blob/master/workshops/README.md
> All we would have to do is update it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/688#issuecomment-181038908>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by sethtrei** [comment]
So can I do a complete overhaul of that README.md?

**Comment by sethtrei** [comment]
done: https://github.com/hackclub/hackclub/pull/697

**Comment by zachlatta** [comment]
:+1:

On Mon, Feb 8, 2016 at 1:04 PM, Seth Treiman <notifications@github.com>
wrote:

> done: #697 <https://github.com/hackclub/hackclub/pull/697>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/688#issuecomment-181539642>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by paked** [comment]
Closing in favour of #697

**Pull request closed without merging**
