### PR TITLE
https://hackclub.slack.com/files/UJMRP65K9/F01ACJP658D/new_vedio.mp4

### PR DESCRIPTION
**Pull request by bezlin6mechminerz**
---
name:'First React App'
description:'Make your First React App from Scratch'
author: '@Bezlin Johnson'
---

# First React app

This will be the website we will make using react.js today.

looklike

Here is the [live_demo](https://electricignorantbrains.bezlin.repl.co) and [final_code](https://repl.it/@bezlin/ElectricIgnorantBrains#src/App.js) (see src/app.js and public/app.css files).
This workshop will take 50 minutes.

### Setting up the environment for react.js

[Repl.it](https://repl.it) is a simple yet powerful online IDE, Editor, Compiler, Interpreter, and REPL. Code, compile, run, and host in 50+ programming languages.So it is super awesome.

To get started, go to https://repl.it/languages/react.js. If you cant find it just type it in the type box. Your coding environment will be ready in a few seconds!
codeeditor

## Step 2: Know the basics of React.js

images

### what is react.js why react.

React is an open-source JavaScript library for building user interfaces or UI components. It is maintained by Facebook and a community of individual developers and companies. React can be used as a base in the development of single-page or mobile applications.
Why react?. React Js is an open-source JavaScript library that is used for building user interfaces specifically for single-page applications. It's used for handling the view layer for web and mobile apps. React also allows us to create reusable UI components. The main purpose of React is to be fast, scalable, and simple.

### App.js

You can find App.js file in the src folder [here](https://repl.it/@bezlin/ElectricIgnorantBrains#src/App.js). This file is the demo file which comes included with react package. There are some codes auto generated by react.
The first 2 lines of code is for importing necessary packages .
ReactDom.render is a function which renders out the elements we put inside it.
we can write basic html inside the render function. And you can also use jsx inside html by putting{ the jsx inside these curly braces}.
So here we need a logo which is the default logo of react .when we open react for the first time the code auto generated gives you a output in which a react logo spins and some lines below .Here we have just increased the speed of the spin and just deleted all lines and print hello world.
html div tag stands for division tag it divides the website into different segments.
img tag is for importing images inside that we specify the url of image as src="url".
className is styling if you know html and css please note in react.js class = className.
Then we printed hello world for that we need h1 tag h stands for heading and 1 stands for the standard size of the heading it can be h1,h2,h3 etc.... upto how smaller you want it.

### App.css

App.css is a styling file which is used to give styling otherwise the app wont look nice. The react logo is spinning and it is the center it is because css plays role there. Here we can give color for h1 elements and make spin the logo etc...
The app.css file contain the stylings for app.js file .You noticed that we use className in the app.js file .Inside the className we specify the name of the object that we will specify in app.css so we can name it maybe logo. Then we go to app.css and call that using .logo{} inside these braces you can specify the pure css thats it simple like html.

## Step 3: Running the code

Click on the green run button on the top thats it.
ezgif com-gif-to-mp4

## OUTPUT

ezgif com-video-to-gif

## Now you made your first react app whats next?

Now you can make it better make a portfolio :) that would be cool.

### Steps

1: pick an editor sublime or vscode etc...
2: install node.js to run react.js install node from [here](https://nodejs.org/en/) go for the LTS version
3: open terminal on mac or cmd on windows .
4: Run the command to create a react app command= (create-react-app appname) you can give any name for the app in the appname .
5: If you are using vscode open it and go to extentions and install simple react snippets, prettier packages.
6: In the terminal it tooks some time to finish creating app after creating you can see happy hacking displayed over there now type these commands (cd appname) this means the react will have created the app packages for you and place it at the folder with the name you have given. So you need to go inside the folder via terminal so we use this command.
7: Inorder to run it run this command on terminal (npm start) This will automaticaly take you to the browser and show you the output there.
8: Open that folder in the vs code You are all set to go.
9: you can add basic html in the render function of the react.js so learn some html and fire up your app you can learn html [here](https://devdocs.io/html/) from there documentation and css [here](https://developer.mozilla.org/en-US/docs/Web/CSS) .

### Now you have completed Your First React App Now you need to host it right?

You need to upload the website to make other people know about your website.
For now lets look at simple hosting the simplest way is on repl.it sign up .And there you can share it.

## Step 4: Your Custom Part

Now you know react a little bit . You should not stop here inorder to learn more and master in react you need to practice a lot. The best way to learn react is look at the world and think of an idea then try to make it. You will learn react soon because its simple .

### Websites made using react.js by other hackers.

[Hariprasad rajan](https://hariprasadrajan.netlify.app)
[Anupriya shaji](https://anupriya.netlify.app)
[Alfred Jophy](https://electricignorantbrains.bezlin.repl.co)
[Bezlin Johnson](https://team7calculator.netlify.app)

## Big platforms made using react.js

Netflix
Instagram
Facebook
Dropbox
Asana
BBC
SalesForce etc....

### CODE REVIEW

**Comment by bezlin6mechminerz** [comment]
hi i don't know much about this process please guide me.

**Comment by bezlin6mechminerz** [comment]
how to do that

**Comment by bezlin6mechminerz** [comment]
please help me

**Review by lachlanjc — CHANGES_REQUESTED** [review]
Hey there! It looks like this PR has a lot of changes that aren't the new workshop. Can you re-fork the repo & add only your new file?

Regarding your workshop—this is a good start, but it's important that workshops help hackers build something visual & obviously cool/interesting/useful. If you've been building web apps without React, React is super cool, but if you're new to coding, I don't think it's inherently obvious why React is so powerful. If you want to use React to make a simple app (we've got two workshops using Next.js already, more would be awesome), that would be more what we're looking for.

I'm closing this for now, but go ahead & open a new PR if/when you've got something new ready. Thanks!

**Comment by bezlin6mechminerz** [comment]
Can I make a python graphical interfaces tutorial will that be accepted

**Comment by lachlanjc** [comment]
Absolutely! Just make sure it’s visual, runs online, & meets the other requirements 👍

**Comment by bezlin6mechminerz** [comment]
ok

**Comment by bezlin6mechminerz** [comment]
what about webviw using html and css to clone other website

**Pull request closed without merging**
