### PR TITLE
Move soundboard script tags into head tag

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by zachlatta** [comment]
This'll block page rendering until the JavaScript loads, which I don't
think we want. Is this what you intend?

On Wed, Apr 20, 2016 at 9:45 AM, Max Wofford <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/hackclub/hackclub/pull/794
> Commit Summary
>
>    - Move soundboard script tags into head tag
>
> File Changes
>
>    - *M* workshops/soundboard/README.md
>    <https://github.com/hackclub/hackclub/pull/794/files#diff-0> (14)
>
> Patch Links:
>
>    - https://github.com/hackclub/hackclub/pull/794.patch
>    - https://github.com/hackclub/hackclub/pull/794.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/794>
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by MaxWofford** [comment]
@zachlatta,this was discussed with @jkwok91 in slack

**Comment by zachlatta** [comment]
What were the conclusions?

**Comment by jkwok91** [comment]
¯\_(ツ)_/¯

**Comment by jkwok91** [comment]
This has been vetoed? Closing.

**Pull request closed without merging**
