### PR TITLE
Change name of example at bottom of Dodge

### PR DESCRIPTION
**Pull request by ssun098**

### CODE REVIEW

**Comment by ssun098** [comment]
Blocks on https://github.com/hackclub/markcop/pull/114

**Comment by MaxWofford** [comment]
@ssun098 Just a heads up, but I think your comment at https://github.com/hackclub/markcop/pull/114#issue-166950798 automatically closed this PR when I merged hackclub/markcop#114. I'm going  to go ahead  and reopen this PR to review it.

**Comment by ssun098** [comment]
@MaxWofford does saying "this issues blocks x" close it when it's resolved?

**Comment by MaxWofford** [comment]
@ssun098 Nope

**Pull request merged**
