### PR TITLE
Add a Fetch that Hack Clubber Workshop

### PR DESCRIPTION
**Pull request by sampoder**
lol, it's a weird one :D

### CODE REVIEW

**Comment by lachlanjc** [comment]
Is this ready to review @sampoder?

**Comment by sampoder** [comment]
Ahhh well, I think the content is ready but I haven't tested it yet (its very awkward asking people to test and I dont want to bother the same people over and over) but I'll try my best to get it tested

**Comment by MatthewStanciu** [comment]
Hey I'm gonna close this for now until it's ready to review. Feel free to reopen when you feel it's ready

**Comment by sampoder** [comment]
coolio

**Comment by sampoder** [comment]
yay!!! @MatthewStanciu I finally did it: https://hackclub.slack.com/archives/C01A9V5LPD0/p1605711835024400

**Comment by MatthewStanciu** [comment]
This is fantastic. Great work 🚀

**Pull request merged**
