### PR TITLE
Add #studycorner to Slack Field Guide

### PR DESCRIPTION
**Pull request by jkwok91**
In response to: https://github.com/hackclub/hackclub/issues/713

### CODE REVIEW

**Comment by zachlatta** [comment]
Can you add a dropshadow to the example screenshot?

**Comment by jkwok91** [comment]
how were the other dropshadows achieved?

**Comment by zachlatta** [comment]
Using GIMP: `Filter > Shadows > Drop Shadow` (or something like that)

**Comment by zachlatta** [comment]
You could probably do something very similar with Photoshop.

**Comment by jkwok91** [comment]
A+
for future reference, i used 40% drop shadow (layer effects) with distance 0 and height 25. then i did image > trim to crop to fit

**Comment by jkwok91** [comment]
:raised_hands:

**Pull request merged**
