### PR TITLE
Add Python Neural Network workshop

### PR DESCRIPTION
**Pull request by JohnLins**
Northgate Club Co-pres, @John Lins, https://hackclub.slack.com/archives/C01A9V5LPD0/p1603147934013300

Create a neural network from scratch.

### CODE REVIEW

**Comment by JohnLins** [comment]
Oops, could someone please change line 76 to: "For those of you who are not fond of calculus, all the "derivative" does essentially is find the slope of any function."

Grammarly messed up the grammar 🤦‍♂️

**Review by lachlanjc — CHANGES_REQUESTED** [review]
Hey, thanks for the submission! Can you remove the image files from this PR & upload to the #cdn channel instead? Make sure there’s alt text on them too.

**Comment by JohnLins** [comment]
Hello Lachlan,
Thank you for reviewing my PR so fast. I'm not sure how to update a pull request, would you like me to make a brand new one?

**Comment by lachlanjc** [comment]
You can push commits back to your same branch, & they’ll show up here. At the top of the PR, click the blue link to your branch, open your file, & you can edit there. You can also go to the Files Changed section, click the ellipsis, & Edit File. Lmk if I can help with that any other way too!

Closing in favor of #1385

**Pull request closed without merging**
