### PR TITLE
Image editor (Workshop bounty)

### PR DESCRIPTION
**Pull request by wollygfx**
I'll send the workshop's video as soon as i can

### CODE REVIEW

**Comment by MatthewStanciu** [comment]
Hey @wollygfx could you remove the 3d models workshop from this PR? It makes reviewing your new workshop a bit more difficult. Let me know once you've done that and once the video is in and I'll start reviewing! This new workshop looks awesome.

**Comment by wollygfx** [comment]
Hey @MatthewStanciu i would do so, but i don't really know how to. Do you have any youtube tutorial or anything that i can see? Thank you😃

**Comment by MatthewStanciu** [comment]
Moving to Slack DMs

**Comment by MatthewStanciu** [comment]
Hey @wollygfx, just did a first pass. I'm super excited to get this on the workshops page, but I think it still has a bit of a long way to go before it's something I can endorse as Hack Club curriculum.

The biggest issue with the workshop right now is that overall it feels a little thrown together, and many parts of it aren't explained very well. One thing I loved about your 3D Models workshop is that for each step, you 1) clearly explained what the step is going to do, 2) pasted a code block, and 3) broke each part of it down and explained it really clearly. Here's an example of what I'm thinking about:

Screen Shot 2020-11-11 at 12 56 36 PM

This is fantastic, and is exactly the kind of stuff that makes great workshops, but I don't really see that in this workshop. Instead, most code blocks look more like this:

Screen Shot 2020-11-11 at 1 00 50 PM

A similar format, but in 1) it doesn't explain what the code you're about to write is going to do, and in 3) the explanation feels a lot more rushed and less clear than it should.

Going through this workshop, I felt like I could understand what individual lines of code did, but I didn't feel like I understood how the app actually works. The first kind of shock I had was at the beginning, when all of a sudden I ended up with an image, a form, and some sliders, all completely styled and everything, and it wasn't 100% clear to me what I actually did or why it all worked. I also don't really love that I seemed to be encouraged to copy/paste code in many places, which I don't think is something that should be encouraged in workshops. And finally, I also wish this workshop checked in a lot more about where you are in the workshop and what your current code should look like. One thing people have started doing that I really like is including `<details>` and putting large checkin code blocks inside there. Here's an example, from [Fayd's latest workshop](https://workshops.hackclub.com/quotes_generator/) (click on the arrow to expand):

Screen Shot 2020-11-11 at 1 10 39 PM

I went through and made a few of these changes myself as kind of an example of what I'm thinking of, but there's still a lot of work for you to do.

I'm going to close this for now, just so that I can easily keep track of which workshops do and don't need my attention, but once you've made these changes, reopen the pull request and DM me on Slack. Also I'm happy to give more tips or work with you on this anytime :) just let me know. 🚀

**Pull request closed without merging**
