### PR TITLE
added my new workshop

### PR DESCRIPTION
**Pull request by ahmed307**
this is my new workshop (gas alerting system )

### CODE REVIEW

**Comment by sampoder** [comment]
@ahmed307 you need to add a lot more content. Check out all the other PRs, I lot have over 300 lines of markdown. You want to start by explaining the steps. Thank you!

**Review by sampoder — CHANGES_REQUESTED** [review]
View above

**Comment by ahmed307** [comment]
Hi ...
I am understanding and working now on what ordered.So, I will make Another
pull request and you can edit on it as you wish. Instead of this one. Okay
?!

**Comment by ahmed307** [comment]
That's if you need to add something by yourself

**Comment by ahmed307** [comment]
And if there is any other changes to do . I'll be happy to hear from you as
this my first workshop and not everything is perfect now.

**Comment by ahmed307** [comment]
hi...
I have edited it. hope it is good now

**Comment by sampoder** [comment]
is this for workshop bounty?

**Comment by ahmed307** [comment]
c

> is this for workshop bounty?

yes

**Comment by ahmed307** [comment]
Excuse me !
I don't know what to do now whether the workshop is good or need some
improvements. And what should I do after that?

**Comment by sampoder** [comment]
Hi Ahmed, no need to get toxic. I apologise for my delay in response. You should check the requirements for the workshop bounty as this workshop does not meet them all.

**Comment by ahmed307** [comment]
Ok. May I have a feedback not to have the same errors in the next time and
avoid them

**Comment by sampoder** [comment]
Check the requirements, and then I (or another reviewer) can give you more feedback

**Comment by sampoder** [comment]
Hey @ahmed307 , just for some housekeeping work on my end, what hack club do you lead?

**Comment by ahmed307** [comment]
hack club STEM sharkya ( branch from hack club Egypt )

**Comment by lachlanjc** [comment]
Hi there! Really appreciate your workshop submission. We should clarify this in the bounty requirements, but we’re not currently accepting hardware workshops, since the majority of clubs won’t have the necessary tools. Additionally, this workshop doesn’t many of the guidelines, such as thoroughly explaining all the steps, demonstrating the final product upfront, giving opportunities for hacking at the end, and it has a number of mistakes/typos. We’d love to see another workshop from you if you’re interested, but this one currently doesn’t meet the guidelines. Thanks.

**Pull request closed without merging**
