### PR TITLE
Add initial draft of Googling to personal website

### PR DESCRIPTION
**Pull request by jonleung**

### CODE REVIEW

**Comment by ad510** [comment]
Why can't Googling be a core part of the workshop instead of an extra section at the end? I think centering the body and changing the font would be good candidates for that, since the web page still looks OK if you skip those steps.

The way you've done it here, it makes it feel like changing the background color is a mandatory part of the workshop instead of an extra optional thing. And I think Googling is a core skill anyway that should be in the main part of the workshop.

Slightly off topic, but now that the workshop is in master, any thoughts on putting the CSS in the <head> instead of an external file? I think that would be easier to do.

**Comment by zachlatta** [comment]
:+1: to @ad510's comments.

> Slightly off topic, but now that the workshop is in master, any thoughts
on putting the CSS in the instead of an external file? I think that would
be easier to do.

I think we should try to use good conventions for file layout when
possible, to avoid any additional confusion. I think it's easier and less
confusing if we start off by introducing CSS as being in a separate file
(telling them why we decided to do that, of course).

On Thu, Feb 11, 2016 at 4:49 PM, Andrew Downing <notifications@github.com>
wrote:

> Why can't Googling be a core part of the workshop instead of an extra
> section at the end? I think centering the body and changing the font would
> be good candidates for that, since the web page still looks OK if you skip
> those steps.
>
> The way you've done it here, it makes it feel like changing the background
> color is a mandatory part of the workshop instead of an extra optional
> thing. And I think Googling is a core skill anyway that should be in the
> main part of the workshop.
>
> Slightly off topic, but now that the workshop is in master, any thoughts
> on putting the CSS in the instead of an external file? I think that would
> be easier to do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/704#issuecomment-183131810>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by jonleung** [comment]
@ad510 re: Googling being a core part of the workshop. Yeah, I actually like that idea! I'll see if I have time to incorporate it.

**Comment by jonleung** [comment]
:+1: to @zachlatta's comment

**Comment by zachlatta** [comment]
Assigning @jkwok91 since @jonleung has left Hack Club.

**Comment by MaxWofford** [comment]
Moved to https://github.com/hackclub/hackclub/pull/718

**Pull request closed without merging**
