### PR TITLE
Convert Twilio to Cloud9

### PR DESCRIPTION
**Pull request by jonleung**

### CODE REVIEW

**Comment by jonleung** [comment]
@zachlatta, if you could do me a favor and fix anything that you see wrong instead of making comments, I would greatly appreciate that : )

**Comment by zachlatta** [comment]
Will submit a PR

--
Zach Latta
Hack Club | zach@hackclub.io

**Comment by zachlatta** [comment]
Just submitted #665.

**Comment by jonleung** [comment]
@zachlatta, I'm not sure which pull request you are referring to?

**Comment by zachlatta** [comment]
I think I meant to say #661.

On Mon, Feb 1, 2016 at 1:29 PM, Jonathan Leung <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta>, I'm not sure which pull
> request you are referring to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/665#issuecomment-178202683>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jonleung** [comment]
@zachlatta, I think you meant this: https://github.com/jonleung/hackclub/pull/2

**Comment by jonleung** [comment]
@zachlatta, I can't figure out what's wrong with this because Twilio is a link:

https://circleci.com/gh/hackclub/hackclub/1356

**Comment by jonleung** [comment]
Other than that it should be good to merge (I merged in all of your fixes)

**Comment by zachlatta** [comment]
The link destination is on a separate line. Markcop only support link destinations on the same line.

Changing that will fix it.

**Comment by jonleung** [comment]
Ok, I fixed the error!

**Comment by jonleung** [comment]
This closes #649

**Comment by paked** [comment]
Taking this off of @zachlatta's hands as discussed on Slack

**Comment by paked** [comment]
I've given this a review and deemed it "not broken".

**Pull request merged**
