### PR TITLE
Create the Maze workshop

### PR DESCRIPTION
**Pull request by jajoosam**
Talked to @zachlatta about this.

### CODE REVIEW

**Comment by zachlatta** [comment]
Thanks @jajoosam. Can you fix the breaking tests?

@MaxWofford / @lachlanjc, can one of you assign yourselves & review this?

**Comment by zachlatta** [comment]
@lachlanjc, can you provide a timeline for reviewing this?

**Comment by MaxWofford** [comment]
@lachlanjc any updates on this?

**Comment by MaxWofford** [comment]
Going to go ahead and close unless there are updates on this

**Comment by MaxWofford** [comment]
Looking back at this I don't think it makes sense to close it. Going to assign myself & make sure it gets reviewed

**Comment by MaxWofford** [comment]
@jajoosam: can you add the images from notion (ex. https://github.com/hackclub/hackclub/pull/1133/files#diff-27f6f06d64411d4bb75a78c6a9cbc9fdR29) to the local repository like how we store images in the personal_website workshop?

**Comment by MaxWofford** [comment]
This was moved to https://github.com/hackclub/hackclub/pull/1150

**Pull request closed without merging**
