### PR TITLE
Change p5 script URL

### PR DESCRIPTION
**Pull request by reicko**

### CODE REVIEW

**Comment by MaxWofford** [comment]
Thanks for the contribution @reicko!

**Comment by MaxWofford** [comment]
This looks good to me, but I'll hold off on merging it so @ZucchiniZe can. @ZucchiniZe, if you need to make any changes would you please rebase @reicko's and make them directly?

**Comment by MaxWofford** [comment]
Just noticed @ZucchiniZe doesn't have permissions to merge this. Assigning myself.

**Comment by MaxWofford** [comment]
I've just updated the branch and brought it to https://github.com/hackclub/hackclub/pull/644. Closing this PR.

**Comment by zachlatta** [comment]
❤

On Sun, Jan 10, 2016 at 3:12 AM, Max Wofford <notifications@github.com>
wrote:

> Closed #642 <https://github.com/hackclub/hackclub/pull/642>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/pull/642#event-510428950>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.io

**Comment by jonleung** [comment]
Thanks so much for the contribution @reicko!

**Comment by reicko** [comment]
NP. If you need anything, just ask !

**Comment by jonleung** [comment]
Definitely @reicko! How did you find out about this repository?

**Comment by reicko** [comment]
I think it was in "My first PR"

**Comment by jonleung** [comment]
<3

**Pull request closed without merging**
