### PR TITLE
Add gif showing how to get public URL for portfolio

### LINKED ISSUE #503: It's unclear how to get the output URL in the Portfolio workshp
When I was running the portfolio workshop in Estonia, about half of the people doing the workshop asked me how to get the output URL from JS Bin in https://github.com/hackedu/hackedu/tree/master/workshops/portfolio#get-a-link-that-everyone-can-see.

/cc @jonleung

### PR DESCRIPTION
**Pull request by paked**
This fixes #503!

### CODE REVIEW

**Comment by paked** [comment]
Assigning @jonleung because it is his workshop :)

**Comment by zachlatta** [comment]
Isn't it actually `Share -> Output only -> Link`?

recorded

**Comment by paked** [comment]
@zachlatta I think they both accomplish the same thing. I'll use your gif.

**Comment by zachlatta** [comment]
Sounds good! It'd be great if you could update it.

Only issue is that this won't be accessible to people using screen readers, though I'm sure there are far worse accessibility issues in our workshops.

**Comment by paked** [comment]
@zachlatta Oh wow. That opens up a whole other set of problems... Lets open an issue for that. (I've just pushed)

**Comment by paked** [comment]
@zachlatta ready to merge :)

**Comment by zachlatta** [comment]
@jonleung ^^

**Comment by zachlatta** [comment]
:+1:

**Pull request merged**
