### PR TITLE
Add workshop : Motion Sensor alarm

### PR DESCRIPTION
**Pull request by Chromico**
Hey I'm made the changes as requested. Again if there is any issue please let me know :) The workshop demo is on Slack.

### CODE REVIEW

**Review by zachlatta — CHANGES_REQUESTED** [review]
Can you link the recording of the test here?

**Comment by Chromico** [comment]
Sure here you go https://hackclub.slack.com/archives/C01A9V5LPD0/p1600182864011900

**Comment by zachlatta** [comment]
Awesome! I'm assigning @MatthewStanciu to be your reviewer on this!

**Comment by lachlanjc** [comment]
Hey! I'm really sorry this has taken so long without good news on this end, I know that's not a great experience. We need to clarify our guidelines, but unfortunately we're not currently accepting hardware workshops, since the majority of clubs won't have the necessary equipment & it's not super easy to acquire. My apologies for not making that clearer upfront. This workshop also doesn't meet several guidelines, such as requiring desktop software, missing alt text on images, & not having a clear demo/explanation of the project at the start. If you'd like to submit another workshop, we'd welcome it.

**Pull request closed without merging**
