### PR TITLE
Orpheus Run (Workshop Bounty)

### PR DESCRIPTION
**Pull request by faisalsayed10**
Follows all the guidelines and here's the demo recording! : https://hackclub.slack.com/archives/C01A9V5LPD0/p1608813022053300

### CODE REVIEW

**Comment by sampoder** [comment]
closing to clear up the pr list coz its stressing me out, happy to review when ready

**Comment by faisalsayed10** [comment]
sure

**Review by sampoder — CHANGES_REQUESTED** [review]
Super super close: https://hackclub.slack.com/archives/C01HW72N481/p1608887085017600

Basically just needs 3 demos at the end instead of 2

**Comment by faisalsayed10** [comment]
alrighty

**Comment by faisalsayed10** [comment]
@sampoder done! :+1: :rocket:

**Comment by sampoder** [comment]
Hmm cant

**Comment by sampoder** [comment]
Oh now i can

**Review by sampoder — APPROVED** [review]
I'm happy with it!

**Pull request merged**
