### PR TITLE
hackide workshop

### PR DESCRIPTION
**Pull request by bajpai244**
I have created a workshop on how to make your own web IDE.
It is super simple and anyone with a knowledge of HTML, CSS, Javascript can make it.
I am a technical intern with Hack Club India and I am _submitting this workshop as a staff member._

If you want to see what people will make in this workshop then go to [https://hackideworkshopdemo.vercel.app/](https://hackideworkshopdemo.vercel.app/)

If you want to check out the repl then go to https://repl.it/@HARSHBAJPAI1/hackidestarter-1#indexhtml

### CODE REVIEW

**Comment by bajpai244** [comment]
Also wanted to add that as I am submitting it as a staff member **so this is not a part of the workshop bounty program.**

**Comment by Matt-Gleich** [comment]
Hey @bajpai244! In the future please use hack club's cdn for images. You can find more info in the #cdn channel on hack club's slack. Thank you!

**Comment by bajpai244** [comment]
Hey @Matt-Gleich! Sure in any future work I will use the CDN.

**Comment by Matt-Gleich** [comment]
Great thank you!

**Pull request merged**
