### PR TITLE
Added Text Adventure Game in Rust

### PR DESCRIPTION
**Pull request by panos**
This is a continuation of [this pull request](https://github.com/hackclub/hackclub/pull/1561).

(Please don't merge this before we rebase/sign the commit, thanks!) :D

### CODE REVIEW

**Comment by panos** [comment]
@sampoder Just so it's clear, are we currently in the stage of waiting for a review?

**Comment by sampoder** [comment]
Yep, but you'll want to mark this as not a draft

**Comment by panos** [comment]
Done, I'm just waiting for the final corrections (if any) before I squash the commits.

**Review by sampoder — CHANGES_REQUESTED** [review]
Thanks for the new submission! I'm a bit confused by the new section, the flow seems to skip to it and it's missing something. Maybe be a more suitable introduction?

At the moment the intro seems to make me think I should have wrote this code.

Hope that makes sense. Feel free to dm me on Slack if it doesn't

- Sam 🚀

**Pull request closed without merging**
