### PR TITLE
Add row to workshops table for thugify workshop

### PR DESCRIPTION
**Pull request by jkwok91**
Includes @JevinSidhu's thugify workshop in master list of workshops

Should have been part of https://github.com/hackclub/hackclub/pull/692

### CODE REVIEW

**Comment by MaxWofford** [comment]
Not sure if I understand the description. What does the workshop involve?

**Comment by jkwok91** [comment]
how about "Using jQuery to add text dynamically to other text"
it adds ", dawg" to text taken from an input field.

**Comment by paked** [comment]
What about "Learn to dynamically modify webpages with jQuery"

**Comment by jkwok91** [comment]
what about "learn to dynamically modify TEXT with jquery"

**Comment by JevinSidhu** [comment]
@jkwok91 @paked  That sounds good!

**Comment by zachlatta** [comment]
Can you squash your commits? :-)

**Comment by jkwok91** [comment]
cloudzwat2

boooooomm

**Pull request merged**
