### PR TITLE
[DNM] [WIP] Add preliminary guidelines

### PR DESCRIPTION
**Pull request by paked**

### CODE REVIEW

**Comment by paked** [comment]
I'm looking through this information and wondering whether it is redundant. If this gets merged, we're going to have 3 different "contribution" related documents.

**Comment by paked** [comment]
#529

**Comment by paked** [comment]
We need to discuss if this is worth it

**Comment by jonleung** [comment]
Assigning this back to @paked as per our discussion yesterday.

**Comment by jonleung** [comment]
I think that it would be worthwhile to include more detailed guidelines on how to make high quality workshops. I don't think `workshop/CONTRIBUTING.md` is thorough enough. However I won't get to working on this until later and I don't think it's too important right now. I'm comfortable with closing this pull request and moving the issue into backlog for now. Thoughts @paked?

**Comment by paked** [comment]
@jonleung SGTM.

**Comment by MaxWofford** [comment]
@paked Is this still active?

**Comment by paked** [comment]
@MaxWofford Waiting for @jonleung to close this.

**Comment by jonleung** [comment]
Opting to just close this since it is not being worked on.

**Pull request closed without merging**
