### PR TITLE
New workshop on how to publish an npm package

### PR DESCRIPTION
**Pull request by bajpai244**
This workshop is on how to write and publish an npm package.
I am writing this workshop as a staff member and it is **not part of the workshop bounty program.**

### CODE REVIEW

**Comment by sampoder** [comment]
@bajpai244 maybe you could use #cdn for the images

**Comment by bajpai244** [comment]
@sampoder  I have discussed this with @MatthewStanciu and he told me it is a neccessity for workshop bounty workshops , so I developed it without using a cdn.

**Comment by sampoder** [comment]
oh ya I gotcha, but still it helps keep repo size down both ways

**Comment by bajpai244** [comment]
Oh! I see the advantage now!! Yes will try to use the cdn next time.

**Pull request merged**
