### PR TITLE
Add Intro to Machine Learning Workshop

### PR DESCRIPTION
**Pull request by harrisbegca**
If anything needs to be added to the readme, please let me know.

### CODE REVIEW

**Comment by polytroper** [comment]
One quick change, the README needs some metadata at the top of the file. Use this one for reference:

https://raw.githubusercontent.com/hackclub/hackclub/master/workshops/feature_extractor/README.md

^^^ Note about the above: *You can ignore the `canonical` metadata field.* That's just for publishing workshops that originally came from other sites, you can safely remove it from your metadata.

**Comment by MaxWofford** [comment]
@polytroper: there isn't any good documentation on how to structure the metadata. want to just do that & merge?

**Comment by MaxWofford** [comment]
> want to just do that

* re-reading this & realizing it's not super clear. I meant, "do you want to just write the metadata yourself"

**Comment by harrisbegca** [comment]
Sure thing!

**Comment by polytroper** [comment]
@harrisbegca Yes please, would appreciate that!

**Comment by harrisbegca** [comment]
Perfect, it should be fixed now!

**Comment by lachlanjc** [comment]
Just reformatted the Markdown with Prettier so it's consistent with the rest of the workshops. Super excited to finally have some Python + ML content, thanks so much @harrisbegca!

**Comment by polytroper** [comment]
Looks good, merging now.

**Pull request merged**
