### PR TITLE
Fix broken profile images

### PR DESCRIPTION
**Pull request by khrj**
Change `@KhushrajRathod` to `@khrj`

### CODE REVIEW

**Review by sampoder — APPROVED** [review]
nice catch! how you been khushraj?

**Comment by khrj** [comment]
I'm doing great! How are you?

**Comment by sampoder** [comment]
Ay, I'm so glad to hear! Just recovered from COVID, but getting back into life which is going as well as it can go. Had a nice extended holiday in Australia which was a positive side effect 🦘

**Comment by cedric-h** [comment]
positive side effect or side effect of being positive :thinking: 

really awesome to see such a positive interaction taking place in github issues hehe

**Comment by sampoder** [comment]
extra two weeks on holiday can never be a bad thing (even if one of them you spend in iso)

**Pull request merged**
