### PR TITLE
Add revised hack club onesheet to hackclub/clubs

### PR DESCRIPTION
**Pull request by CoolBeans19**
Onesheet that gives a brief overview of what hack club does. Useful for teachers who want a simple introduction to hack club.

### CODE REVIEW

**Comment by CoolBeans19** [comment]
Yo yo yo! Can I get some final feedback on this thing? Let's get it polished off and get it in!

**Comment by paked** [comment]
> When we say "hack", we're referring to "life hack" type of hacking

You're missing a 'the', I'd say.

**Comment by CoolBeans19** [comment]
@paked good catch :ok_hand:

**Comment by paked** [comment]
Some more thoughts:

- Put another new line between the paragraphs in the first section.

**Comment by CoolBeans19** [comment]
@paked Integrated your suggested changes, have anything else?

**Comment by paked** [comment]
> Since its conception...

I think you might be looking for "inception" there. Inception is "at the beginning", conception is "moment of birth". At least, that's how we use those in Australia.

**Comment by CoolBeans19** [comment]
Going to take @zachlatta's suggestion and add images to the bubbles, change some of the content

**Comment by CoolBeans19** [comment]
take a gander yo

**Comment by CoolBeans19** [comment]
I am satisfied with what I have so far. Any last suggestions or text revisions @zachlatta?

**Comment by zachlatta** [comment]
I think you may have accidentally squashed your additions for this PR with a merge commit. Can you work with @MaxWofford to fix the commit for this pull request?

Other than that, ready for merge. Just ping me when the commit is fixed and I'll get it into master.

**Comment by zachlatta** [comment]
Assigning back to you while you're prepping it to merge.

**Comment by zachlatta** [comment]
@MaxWofford can you with with @CoolBeans19 today to get this ready to merge? Eager to get this into master :-).

**Comment by CoolBeans19** [comment]
@zachlatta tests passed, just about ready to merge. Want to have the honor?

**Pull request merged**
