### PR TITLE
Revert "Debugged image_editor workshop code."

### PR DESCRIPTION
**Pull request by alialiwa2005**
Reverts hackclub/hackclub#1706, formatting is broken... I'll try to fix it soon.

### CODE REVIEW

**Review by sampoder — COMMENTED** [review]
My bad, thanks.

**Comment by alialiwa2005** [comment]
Formatting is broken on the workshop page.
Screenshot_20210220-220120_Chrome

**Comment by alialiwa2005** [comment]
@sampoder, after the revert, the display is still not showing correctly. 
image

I'm not sure what's wrong with the code.

**Comment by alialiwa2005** [comment]
Here, too:

image

**Comment by sampoder** [comment]
I'll handle it. Thanks.

**Pull request merged**
